//! **The names this client answers, as data.**
//!
//! Five arrays — the globals, widget methods, stubs and fired events of the
//! renderer's Lua API — checked against actual registration by the test in
//! `crates/client/src/lua/manifest.rs`, which fails and prints the corrected
//! array whenever one disagrees.
//!
//! ## Why this crate exists
//!
//! `vale framexml` reports the gap between what `Interface\FrameXML\` calls
//! and what this client answers. To do that it needs the client's API surface —
//! and it deliberately does **not** depend on `vale-client`, because that
//! would put Bevy, wgpu and mlua behind a headless tool that currently builds in
//! seconds. So for several rounds the CLI carried a hand-transcribed copy of
//! five arrays.
//!
//! **Every one of those copies was found stale at least once, and each time it
//! reported a confident number that was wrong**: `FIRED` was 35 names behind,
//! `METHODS` 15, `GLOBALS` 7. A list that provably drifts is a bug generator
//! rather than a maintenance cost, and the numbers it produced ("this client
//! answers 244") were read and believed.
//!
//! One copy now, in a crate both sides depend on, with the renderer's own test
//! asserting it against **actual registration** rather than against another
//! list. Staleness is a failing `cargo test --workspace`, which is the only
//! form of "cannot go stale" that survives contact with a real round.
//!
//! ## Why these are supersets, and why that is safe
//!
//! [`GLOBALS`] is every global a fully-installed Lua state holds — the base
//! library, this client's registered verbs and reads, the glue's and the
//! character-creation screen's included, even though `vale framexml` is a
//! report about `Interface\FrameXML\` and will never see a glue name called.
//!
//! That is deliberate. The report intersects these arrays with the names the
//! directory actually calls, so **a name here that the directory never calls
//! costs nothing, and a name missing from here is over-reported as a gap.** The
//! two errors are not symmetric, so the list errs in the direction that cannot
//! lie. Excluding the glue names is what produced the trainer-shaped hole that
//! `GLOBALS` carried for several rounds.

/// **Every global a fully-installed Lua state holds.**
///
/// The base library 1.12 opens (and the flat 5.0 aliases this client puts back
/// on top of it — `format`, `strlen`, `tinsert`), every verb and read the
/// renderer registers, and the stubs. Derived by diffing the globals table
/// across a full `LuaHost::new()` plus one scoped `api::install`.
pub const GLOBALS: &[&str] = &[
    "AbandonQuest", "AbandonSkill", "AcceptContest", "AcceptDuel", 
    "AcceptEULA", "AcceptGroup", "AcceptGuild", "AcceptQuest", 
    "AcceptResurrect", "AcceptScanning", "AcceptSkillUps", "AcceptTOS", 
    "AcceptTrade", "AcceptXPLoss", "ActionHasRange", "AddChatWindowChannel", 
    "AddFriend", "AddIgnore", "AddOrDelIgnore", "AddQuestWatch", 
    "AddSkillUp", "AddTradeMoney", "AssistUnit", "AttackTarget", 
    "AutoEquipCursorItem", "BankButtonIDToInvSlotID", "BeginTrade", "BuyGuildCharter", 
    "BuyMerchantItem", "BuyStableSlot", "BuyTrainerService", "BuybackItem", 
    "CameraOrSelectOrMoveStart", "CameraOrSelectOrMoveStop", "CameraZoomIn", "CameraZoomOut", 
    "CanEditGuildInfo", "CanEditMOTD", "CanEditOfficerNote", "CanEditPublicNote", 
    "CanGuildDemote", "CanGuildInvite", "CanGuildPromote", "CanGuildRemove", 
    "CanInspect", "CanShowResetInstances", "CanSignPetition", "CanViewOfficerNote", 
    "CancelDuel", "CancelLogout", "CancelPlayerBuff", "CancelRealmListQuery", 
    "CancelSkillUps", "CancelTrade", "CancelTradeAccept", "CastPetAction", 
    "CastShapeshiftForm", "CastSpell", "ChangeActionBarPage", "ChangeRealm", 
    "ChannelBan", "ChannelInvite", "ChannelKick", "ChannelModerate", 
    "ChannelModerator", "ChannelMute", "ChannelSilence", "ChannelToggleAnnouncements", 
    "ChannelUnSilence", "ChannelUnban", "ChannelUnmoderator", "ChannelUnmute", 
    "ChannelVoiceOff", "CheckBinderDist", "CheckInbox", "CheckInteractDistance", 
    "CheckPetUntrainerDist", "CheckSpiritHealerDist", "ClearCursor", "ClearInspectPlayer", 
    "ClearSendMail", "ClearTarget", "ClearTutorials", "ClickSendMailItemButton", 
    "ClickStablePet", "ClickTargetTradeButton", "ClickTradeButton", "CloseBankFrame", 
    "CloseCraft", "CloseGossip", "CloseGuildRegistrar", "CloseItemText", 
    "CloseLoot", "CloseMail", "CloseMerchant", "ClosePetStables", 
    "ClosePetition", "CloseQuest", "CloseTabardCreation", "CloseTaxiMap", 
    "CloseTrade", "CloseTradeSkill", "CloseTrainer", "CollapseCraftSkillLine", 
    "CollapseFactionHeader", "CollapseQuestHeader", "CollapseSkillHeader", "CollapseTradeSkillSubClass", 
    "CollapseTrainerSkillLine", "CompleteQuest", "ConfirmAcceptQuest", "ConfirmBinder", 
    "ConfirmLootRoll", "ConfirmPetUnlearn", "ConfirmReadyCheck", "ConfirmSummon", 
    "ContainerIDToInventoryID", "ContestAccepted", "ConvertToRaid", "CreateCharacter", 
    "CreateFrame", "CreateWorldMapArrowFrame", "CursorHasItem", "CursorHasSpell", 
    "CycleCharCustomization", "DeclineGroup", "DeclineGuild", "DeclineQuest", 
    "DeclineResurrect", "DefaultServerLogin", "DelIgnore", "DeleteCharacter", 
    "DeleteCursorItem", "DeleteInboxItem", "DemoteAssistant", "DisableAddOn", 
    "DisableAllAddOns", "DisconnectFromServer", "DisplayChannelOwner", "DoCraft", 
    "DoEmote", "DoReadyCheck", "DoTradeSkill", "EULAAccepted", 
    "EnableAddOn", "EnableAllAddOns", "EnterWorld", "EnumerateServerChannels", 
    "ExpandCraftSkillLine", "ExpandFactionHeader", "ExpandQuestHeader", "ExpandSkillHeader", 
    "ExpandTradeSkillSubClass", "ExpandTrainerSkillLine", "FactionToggleAtWar", "FlagTutorial", 
    "FollowUnit", "ForceQuit", "GetAbandonQuestItems", "GetAbandonQuestName", 
    "GetActionBarToggles", "GetActionCooldown", "GetActionCount", "GetActionText", 
    "GetActionTexture", "GetActiveTitle", "GetAddOnDependencies", "GetAddOnEnableState", 
    "GetAddOnInfo", "GetAddOnMetadata", "GetAdjustedSkillPoints", "GetAvailableRaces", 
    "GetAvailableTitle", "GetBagName", "GetBankSlotCost", "GetBillingPlan", 
    "GetBillingTimeRemaining", "GetBindLocation", "GetBinding", "GetBindingAction", 
    "GetBindingKey", "GetBonusBarOffset", "GetBuildInfo", "GetBuybackItemInfo", 
    "GetCVar", "GetCVarDefault", "GetChannelList", "GetChannelName", 
    "GetCharacterCreateFacing", "GetCharacterInfo", "GetCharacterListUpdate", "GetCharacterSelectFacing", 
    "GetChatWindowChannels", "GetChatWindowMessages", "GetClassesForRace", "GetCoinIcon", 
    "GetContainerItemCooldown", "GetContainerItemInfo", "GetContainerItemLink", "GetContainerNumSlots", 
    "GetCorpseMapPosition", "GetCorpseRecoveryDelay", "GetCraftButtonToken", "GetCraftDescription", 
    "GetCraftDisplaySkillLine", "GetCraftIcon", "GetCraftInfo", "GetCraftItemLink", 
    "GetCraftName", "GetCraftNumReagents", "GetCraftReagentInfo", "GetCraftReagentItemLink", 
    "GetCraftSelectionIndex", "GetCraftSpellFocus", "GetCurrentBindingSet", "GetCurrentMapContinent", 
    "GetCurrentMapZone", "GetCursorPosition", "GetFacialHairCustomization", "GetFactionForRace", 
    "GetFactionInfo", "GetFirstTradeSkill", "GetFramerate", "GetFriendInfo", 
    "GetGameTime", "GetGossipActiveQuests", "GetGossipAvailableQuests", "GetGossipOptions", 
    "GetGossipText", "GetGreetingText", "GetGuildCharterCost", "GetGuildInfo", 
    "GetGuildInfoText", "GetGuildRosterInfo", "GetGuildRosterLastOnline", "GetGuildRosterMOTD", 
    "GetGuildRosterSelection", "GetGuildRosterShowOffline", "GetHairCustomization", "GetIgnoreName", 
    "GetInboxHeaderInfo", "GetInboxInvoiceInfo", "GetInboxItem", "GetInboxNumItems", 
    "GetInboxText", "GetInspectHonorData", "GetInspectPVPRankProgress", "GetInventoryItemBroken", 
    "GetInventoryItemCooldown", "GetInventoryItemCount", "GetInventoryItemLink", "GetInventoryItemQuality", 
    "GetInventoryItemTexture", "GetInventorySlotInfo", "GetItemCount", "GetItemInfo", 
    "GetItemQualityColor", "GetLootMethod", "GetLootRollItemInfo", "GetLootRollItemLink", 
    "GetLootRollTimeLeft", "GetLootSlotInfo", "GetLootSlotLink", "GetLootThreshold", 
    "GetMapContinents", "GetMapInfo", "GetMapLandmarkInfo", "GetMapOverlayInfo", 
    "GetMapZones", "GetMerchantItemInfo", "GetMerchantItemLink", "GetMerchantItemMaxStack", 
    "GetMerchantNumItems", "GetMinimapZoneText", "GetMoney", "GetMouseFocus", 
    "GetNameForRace", "GetNextStableSlotCost", "GetNumActiveQuests", "GetNumAddOns", 
    "GetNumAvailableQuests", "GetNumBankSlots", "GetNumBindings", "GetNumBuybackItems", 
    "GetNumCharacters", "GetNumCrafts", "GetNumFactions", "GetNumFriends", 
    "GetNumGuildMembers", "GetNumIgnores", "GetNumLootItems", "GetNumMapOverlays", 
    "GetNumPackages", "GetNumPartyMembers", "GetNumPetitionNames", "GetNumQuestChoices", 
    "GetNumQuestItems", "GetNumQuestLeaderBoards", "GetNumQuestLogChoices", "GetNumQuestLogEntries", 
    "GetNumQuestLogRewards", "GetNumQuestRewards", "GetNumQuestWatches", "GetNumRaidMembers", 
    "GetNumRealms", "GetNumRoutes", "GetNumShapeshiftForms", "GetNumSkillLines", 
    "GetNumSpellTabs", "GetNumStablePets", "GetNumStableSlots", "GetNumStationeries", 
    "GetNumTalentTabs", "GetNumTalents", "GetNumTradeSkills", "GetNumTrainerServices", 
    "GetNumWhoResults", "GetNumWorldStateUI", "GetObjectiveText", "GetPackageInfo", 
    "GetPartyLeaderIndex", "GetPartyMember", "GetPetActionCooldown", "GetPetActionInfo", 
    "GetPetActionsUsable", "GetPetExperience", "GetPetFoodTypes", "GetPetHappiness", 
    "GetPetIcon", "GetPetLoyalty", "GetPetTrainingPoints", "GetPetitionInfo", 
    "GetPetitionNameInfo", "GetPlayerBuff", "GetPlayerBuffApplications", "GetPlayerBuffDispelType", 
    "GetPlayerBuffTexture", "GetPlayerBuffTimeLeft", "GetPlayerMapPosition", "GetPlayerTradeMoney", 
    "GetProgressText", "GetQuestGreenRange", "GetQuestIndexForWatch", "GetQuestItemInfo", 
    "GetQuestLogChoiceInfo", "GetQuestLogLeaderBoard", "GetQuestLogPushable", "GetQuestLogQuestText", 
    "GetQuestLogRequiredMoney", "GetQuestLogRewardInfo", "GetQuestLogRewardMoney", "GetQuestLogRewardSpell", 
    "GetQuestLogSelection", "GetQuestLogTimeLeft", "GetQuestMoneyToGet", "GetQuestReward", 
    "GetQuestText", "GetRaidRosterInfo", "GetRaidRosterSelection", "GetRaidTargetIndex", 
    "GetRandomName", "GetRealZoneText", "GetRealmCategories", "GetRealmInfo", 
    "GetRealmName", "GetReleaseTimeRemaining", "GetResSicknessDuration", "GetRewardMoney", 
    "GetRewardSpell", "GetRewardText", "GetSavedAccountName", "GetScreenHeight", 
    "GetScreenWidth", "GetScriptMemory", "GetSelectedCategory", "GetSelectedClass", 
    "GetSelectedFaction", "GetSelectedFriend", "GetSelectedIgnore", "GetSelectedRace", 
    "GetSelectedSex", "GetSelectedSkill", "GetSelectedStablePet", "GetSelectedStationeryTexture", 
    "GetSendMailCOD", "GetSendMailMoney", "GetServerName", "GetShapeshiftFormCooldown", 
    "GetShapeshiftFormInfo", "GetSkillLineInfo", "GetSpellCooldown", "GetSpellName", 
    "GetSpellTabInfo", "GetSpellTexture", "GetStablePetFoodTypes", "GetStablePetInfo", 
    "GetStationeryInfo", "GetSubZoneText", "GetSummonConfirmAreaName", "GetSummonConfirmSummoner", 
    "GetSummonConfirmTimeLeft", "GetTabardCreationCost", "GetTabardInfo", "GetTalentInfo", 
    "GetTalentPrereqs", "GetTalentTabInfo", "GetTargetTradeMoney", "GetTime", 
    "GetTitleText", "GetTradePlayerItemInfo", "GetTradePlayerItemLink", "GetTradeSkillCooldown", 
    "GetTradeSkillIcon", "GetTradeSkillInfo", "GetTradeSkillInvSlotFilter", "GetTradeSkillInvSlots", 
    "GetTradeSkillItemLink", "GetTradeSkillLine", "GetTradeSkillNumMade", "GetTradeSkillNumReagents", 
    "GetTradeSkillReagentInfo", "GetTradeSkillReagentItemLink", "GetTradeSkillSelectionIndex", "GetTradeSkillSubClassFilter", 
    "GetTradeSkillSubClasses", "GetTradeSkillTools", "GetTradeTargetItemInfo", "GetTradeTargetItemLink", 
    "GetTradeskillRepeatCount", "GetTrainerGreetingText", "GetTrainerSelectionIndex", "GetTrainerServiceAbilityReq", 
    "GetTrainerServiceCost", "GetTrainerServiceDescription", "GetTrainerServiceIcon", "GetTrainerServiceInfo", 
    "GetTrainerServiceLevelReq", "GetTrainerServiceNumAbilityReq", "GetTrainerServiceSkillLine", "GetTrainerServiceSkillReq", 
    "GetTrainerServiceStepReq", "GetTrainerServiceTypeFilter", "GetTrainerSkillLineFilter", "GetWatchedFactionInfo", 
    "GetWhoInfo", "GetWorldDetail", "GetWorldStateUIInfo", "GetXPExhaustion", 
    "GetZonePVPInfo", "GetZoneText", "GuildControlAddRank", "GuildControlDelRank", 
    "GuildControlGetNumRanks", "GuildControlGetRankFlags", "GuildControlGetRankName", "GuildControlSaveRank", 
    "GuildControlSetRank", "GuildControlSetRankFlag", "GuildDemoteByName", "GuildDisband", 
    "GuildInfo", "GuildInviteByName", "GuildLeave", "GuildPromoteByName", 
    "GuildRoster", "GuildRosterSetOfficerNote", "GuildRosterSetPublicNote", "GuildSetLeaderByName", 
    "GuildSetMOTD", "GuildUninviteByName", "HasAction", "HasCharCustomization", 
    "HasInspectHonorData", "HasNewMail", "HasPetSpells", "HasPetUI", 
    "HasWandEquipped", "HideRepairCursor", "InRepairMode", "InboxItemCanDelete", 
    "InitiateTrade", "InviteByName", "IsActionInRange", "IsAddOnLoadOnDemand", 
    "IsAddOnLoaded", "IsAddonVersionCheckEnabled", "IsAltKeyDown", "IsAttackAction", 
    "IsAutoRepeatAction", "IsConnectedToServer", "IsConsumableAction", "IsControlKeyDown", 
    "IsCurrentAction", "IsCurrentCast", "IsCurrentQuestFailed", "IsEquippedAction", 
    "IsFactionInactive", "IsFishingLoot", "IsGuildLeader", "IsInGuild", 
    "IsInventoryItemLocked", "IsPartyLeader", "IsPetAttackActive", "IsQuestCompletable", 
    "IsQuestWatched", "IsRaidLeader", "IsRaidOfficer", "IsShiftKeyDown", 
    "IsSpellPassive", "IsTalentTrainer", "IsTradeskillTrainer", "IsTrainerServiceLearnSpell", 
    "IsUsableAction", "ItemTextGetCreator", "ItemTextGetItem", "ItemTextGetMaterial", 
    "ItemTextGetPage", "ItemTextGetText", "ItemTextHasNextPage", "ItemTextNextPage", 
    "ItemTextPrevPage", "JoinChannelByName", "Jump", "LaunchAddOnURL", 
    "LaunchURL", "LearnTalent", "LeaveChannelByName", "LeaveParty", 
    "ListChannelByName", "ListChannels", "LoadAddOn", "LoadBindings", 
    "Logout", "LootSlot", "LootSlotIsCoin", "LootSlotIsItem", 
    "MoveBackwardStart", "MoveBackwardStop", "MoveForwardStart", "MoveForwardStop", 
    "NotifyInspect", "NumTaxiNodes", "OfferPetition", "PI", 
    "PINEntered", "PetAbandon", "PetAttack", "PetCanBeAbandoned", 
    "PetCanBeRenamed", "PetHasActionBar", "PetRename", "PetStopAttack", 
    "PickupAction", "PickupBagFromSlot", "PickupContainerItem", "PickupInventoryItem", 
    "PickupPetAction", "PickupSpell", "PickupStablePet", "PitchDownStart", 
    "PitchDownStop", "PitchUpStart", "PitchUpStop", "PlaceAction", 
    "PlayCreditsMusic", "PlayGlueMusic", "PlayMusic", "PlaySound", 
    "PlaySoundFile", "PlayerHasSpells", "PositionWorldMapArrowFrame", "ProcessMapClick", 
    "PromoteByName", "PromoteToAssistant", "PromoteToPartyLeader", "PurchaseSlot", 
    "PutItemInBackpack", "PutItemInBag", "QuestLogPushQuest", "Quit", 
    "QuitGame", "RandomRoll", "RandomizeCharCustomization", "RealmListUpdateRate", 
    "RegisterForSave", "ReloadUI", "RemoveChatWindowChannel", "RemoveFriend", 
    "RemoveQuestWatch", "RemoveSkillUp", "RenameCharacter", "RenamePetition", 
    "RepairAllItems", "RepopMe", "RequestInspectHonorData", "RequestRealmList", 
    "RequestTimePlayed", "ResetAddOns", "ResetCharCustomize", "ResetCursor", 
    "ResetInstances", "ResetTutorials", "ResurrectGetOfferer", "ResurrectHasSickness", 
    "ResurrectHasTimer", "RetrieveCorpse", "ReturnInboxItem", "RollOnLoot", 
    "RunBinding", "RunScript", "SaveAddOns", "SaveBindings", 
    "ScanningAccepted", "Screenshot", "SelectActiveQuest", "SelectAvailableQuest", 
    "SelectCharacter", "SelectCraft", "SelectGossipActiveQuest", "SelectGossipAvailableQuest", 
    "SelectGossipOption", "SelectPackage", "SelectQuestLogEntry", "SelectStationery", 
    "SelectTradeSkill", "SelectTrainerService", "SendChatMessage", "SendMail", 
    "SendWho", "SetAbandonQuest", "SetActionBarToggles", "SetAddonVersionCheck", 
    "SetBagPortaitTexture", "SetBinding", "SetCVar", "SetChannelOwner", 
    "SetChannelPassword", "SetCharCustomizeBackground", "SetCharCustomizeFrame", "SetCharSelectBackground", 
    "SetCharSelectModelFrame", "SetCharacterCreateFacing", "SetCharacterSelectFacing", "SetCurrentScreen", 
    "SetCursor", "SetFactionActive", "SetFactionInactive", "SetGuildInfoText", 
    "SetGuildRosterSelection", "SetGuildRosterShowOffline", "SetMapToCurrentZone", "SetMapZoom", 
    "SetPetStablePaperdoll", "SetPortraitTexture", "SetPortraitToTexture", "SetPreferredInfo", 
    "SetRaidRosterSelection", "SetRaidSubgroup", "SetRaidTarget", "SetSavedAccountName", 
    "SetScriptMemory", "SetSelectedClass", "SetSelectedFaction", "SetSelectedFriend", 
    "SetSelectedIgnore", "SetSelectedRace", "SetSelectedSex", "SetSelectedSkill", 
    "SetSendMailCOD", "SetSendMailMoney", "SetTaxiMap", "SetTradeMoney", 
    "SetTradeSkillInvSlotFilter", "SetTradeSkillSubClassFilter", "SetTrainerServiceTypeFilter", "SetTrainerSkillLineFilter", 
    "SetWatchedFactionIndex", "SetWhoToUI", "ShowCloak", "ShowContainerSellCursor", 
    "ShowContestNotice", "ShowCursor", "ShowEULANotice", "ShowFriends", 
    "ShowHelm", "ShowInspectCursor", "ShowMerchantSellCursor", "ShowRepairCursor", 
    "ShowScanningNotice", "ShowTOSNotice", "ShowWorldMapArrowFrame", "ShowingCloak", 
    "ShowingHelm", "SignPetition", "SitOrStand", "SortGuildRoster", 
    "SortRealms", "SpellCanTargetUnit", "SpellIsTargeting", "SpellStopCasting", 
    "SpellStopTargeting", "SpellTargetUnit", "SplitContainerItem", "StartDuel", 
    "StartDuelUnit", "StatusDialogClick", "StopGlueMusic", "StopMusic", 
    "StrafeLeftStart", "StrafeLeftStop", "StrafeRightStart", "StrafeRightStop", 
    "SurveyNotificationDone", "SwapRaidSubgroup", "TOSAccepted", "TakeInboxItem", 
    "TakeInboxMoney", "TakeInboxTextItem", "TakeTaxiNode", "TargetLastEnemy", 
    "TargetNearestEnemy", "TargetNearestFriend", "TargetUnit", "TaxiGetDestX", 
    "TaxiGetDestY", "TaxiGetSrcX", "TaxiGetSrcY", "TaxiNodeCost", 
    "TaxiNodeGetType", "TaxiNodeName", "TaxiNodePosition", "TaxiNodeSetCurrent", 
    "ToggleAutoRun", "TogglePetAutocast", "ToggleRun", "ToggleSheath", 
    "TurnInGuildCharter", "TurnLeftStart", "TurnLeftStop", "TurnOrActionStart", 
    "TurnOrActionStop", "TurnRightStart", "TurnRightStop", "TutorialsEnabled", 
    "UninviteByName", "UninviteFromParty", "UninviteFromRaid", "UnitAffectingCombat", 
    "UnitArmor", "UnitAttackBothHands", "UnitAttackPower", "UnitAttackSpeed", 
    "UnitBuff", "UnitCanAssist", "UnitCanAttack", "UnitCanCooperate", 
    "UnitCharacterPoints", "UnitClass", "UnitClassification", "UnitCreatureFamily", 
    "UnitCreatureType", "UnitDamage", "UnitDebuff", "UnitDefense", 
    "UnitExists", "UnitFactionGroup", "UnitHealth", "UnitHealthMax", 
    "UnitInRaid", "UnitIsConnected", "UnitIsDead", "UnitIsDeadOrGhost", 
    "UnitIsEnemy", "UnitIsFriend", "UnitIsGhost", "UnitIsPVP", 
    "UnitIsPartyLeader", "UnitIsPlayer", "UnitIsUnit", "UnitIsVisible", 
    "UnitLevel", "UnitMana", "UnitManaMax", "UnitName", 
    "UnitOnTaxi", "UnitPVPName", "UnitPlayerControlled", "UnitPlayerOrPetInRaid", 
    "UnitPowerType", "UnitRace", "UnitRangedAttack", "UnitRangedAttackPower", 
    "UnitRangedDamage", "UnitReaction", "UnitResistance", "UnitSex", 
    "UnitStat", "UnitXP", "UnitXPMax", "UpdateCustomizationScene", 
    "UpdateMapHighlight", "UpdateSelectionCustomizationScene", "UpdateSpells", "UpdateWorldMapArrowFrames", 
    "UseAction", "UseContainerItem", "UseInventoryItem", "ZoomOut", 
    "_G", "_VERSION", "abs", "assert", 
    "ceil", "collectgarbage", "coroutine", "date", 
    "dofile", "error", "floor", "foreach", 
    "foreachi", "format", "gcinfo", "getfenv", 
    "getglobal", "getmetatable", "getn", "gfind", 
    "gsub", "ipairs", "load", "loadfile", 
    "loadstring", "math", "max", "min", 
    "mod", "newproxy", "next", "pairs", 
    "pcall", "print", "random", "rawequal", 
    "rawget", "rawset", "select", "setfenv", 
    "setglobal", "setmetatable", "setn", "sort", 
    "sqrt", "strbyte", "strchar", "strfind", 
    "string", "strlen", "strlower", "strrep", 
    "strsub", "strupper", "table", "time", 
    "tinsert", "tonumber", "tostring", "tremove", 
    "type", "unpack", "xpcall", 
];

/// **Every method a frame or a region carries.**
///
/// Answered by a different mechanism from [`GLOBALS`] — a metatable on the
/// widget object rather than an entry in the globals table — and reported
/// separately for that reason. Derived by enumerating the metatables of a live
/// `Frame` and a live `Texture`.
pub const METHODS: &[&str] = &[
    "AddDoubleLine", "AddHistoryLine", "AddLine", "AddMessage", 
    "AdvanceTime", "AtBottom", "AtTop", "CanSaveTabardNow", 
    "Clear", "ClearAllPoints", "ClearFocus", "ClearFog", 
    "ClearLines", "ClearModel", "Click", "CreateFontString", 
    "CreateTexture", "CycleVariation", "Disable", "DisableDrawLayer", 
    "Enable", "EnableDrawLayer", "EnableKeyboard", "EnableMouse", 
    "EnableMouseWheel", "FadeOut", "GetAlpha", "GetBackdrop", 
    "GetBackdropBorderColor", "GetBackdropColor", "GetBlendMode", "GetBottom", 
    "GetButtonState", "GetCenter", "GetChecked", "GetChildren", 
    "GetDisabledTexture", "GetDrawLayer", "GetFacing", "GetFogColor", 
    "GetFogFar", "GetFogNear", "GetFontObject", "GetFontString", 
    "GetFrameLevel", "GetFrameStrata", "GetHeight", "GetHighlightTexture", 
    "GetHitRectInsets", "GetHorizontalScrollRange", "GetID", "GetInputLanguage", 
    "GetLeft", "GetLowerBackgroundFileName", "GetLowerEmblemFileName", "GetLowerEmblemTexture", 
    "GetMinMaxValues", "GetModel", "GetName", "GetNormalTexture", 
    "GetNumChildren", "GetNumMessages", "GetNumPoints", "GetNumRegions", 
    "GetNumber", "GetObjectType", "GetOrientation", "GetOwner", 
    "GetParent", "GetPingPosition", "GetPoint", "GetPushedTexture", 
    "GetRegions", "GetRight", "GetScript", "GetScrollChild", 
    "GetStatusBarColor", "GetStatusBarTexture", "GetStringHeight", "GetStringWidth", 
    "GetText", "GetTextColor", "GetTextHeight", "GetTextWidth", 
    "GetTexture", "GetThumbTexture", "GetTop", "GetUpperBackgroundFileName", 
    "GetUpperEmblemFileName", "GetUpperEmblemTexture", "GetValue", "GetVertexColor", 
    "GetVerticalScroll", "GetVerticalScrollRange", "GetWidth", "GetZoom", 
    "GetZoomLevels", "HasFocus", "HasScript", "Hide", 
    "HighlightText", "InitializeTabardColors", "Insert", "IsClampedToScreen", 
    "IsEnabled", "IsEventRegistered", "IsFrameType", "IsKeyboardEnabled", 
    "IsMouseEnabled", "IsMouseOver", "IsMouseWheelEnabled", "IsMovable", 
    "IsObjectType", "IsOwned", "IsResizable", "IsShown", 
    "IsUserPlaced", "IsVisible", "LockHighlight", "Lower", 
    "NumLines", "PageDown", "PageUp", "PingLocation", 
    "Raise", "RegisterEvent", "RegisterForClicks", "RegisterForDrag", 
    "Save", "ScrollDown", "ScrollToBottom", "ScrollToTop", 
    "ScrollUp", "SetAction", "SetAllPoints", "SetAlpha", 
    "SetAltArrowKeyMode", "SetAutoFocus", "SetBackdrop", "SetBackdropBorderColor", 
    "SetBackdropColor", "SetBagItem", "SetBlendMode", "SetBlipTexture", 
    "SetButtonState", "SetBuybackItem", "SetCamera", "SetChecked", 
    "SetClampRectInsets", "SetClampedToScreen", "SetCraftItem", "SetCraftSpell", 
    "SetDisabledTexture", "SetDrawLayer", "SetFacing", "SetFadeDuration", 
    "SetFading", "SetFocus", "SetFogColor", "SetFogFar", 
    "SetFogNear", "SetFont", "SetFontObject", "SetFrameLevel", 
    "SetFrameStrata", "SetGradientAlpha", "SetHeight", "SetHighlightTexture", 
    "SetHitRectInsets", "SetHyperlink", "SetID", "SetInboxItem", 
    "SetInventoryItem", "SetJustifyH", "SetJustifyV", "SetLight", 
    "SetLootItem", "SetLootRollItem", "SetMaskTexture", "SetMaxLetters", 
    "SetMaxLines", "SetMaxResize", "SetMerchantItem", "SetMinMaxValues", 
    "SetMinResize", "SetMinimumWidth", "SetModel", "SetModelScale", 
    "SetMovable", "SetMultiLine", "SetNormalTexture", "SetNumber", 
    "SetOrientation", "SetOwner", "SetPadding", "SetParent", 
    "SetPetAction", "SetPlayerBuff", "SetPoint", "SetPosition", 
    "SetPushedTexture", "SetQuestItem", "SetQuestLogItem", "SetQuestLogRewardSpell", 
    "SetQuestRewardSpell", "SetResizable", "SetRotation", "SetScript", 
    "SetScrollChild", "SetSendMailItem", "SetSequence", "SetSequenceTime", 
    "SetShadowColor", "SetShadowOffset", "SetSlot", "SetSpell", 
    "SetStatusBarColor", "SetStatusBarTexture", "SetTalent", "SetTexCoord", 
    "SetText", "SetTextColor", "SetTextHeight", "SetTextInsets", 
    "SetTexture", "SetThumbTexture", "SetTimeVisible", "SetTradePlayerItem", 
    "SetTradeSkillItem", "SetTradeTargetItem", "SetTrainerService", "SetUnit", 
    "SetUnitBuff", "SetUnitDebuff", "SetUserPlaced", "SetValue", 
    "SetValueStep", "SetVertexColor", "SetVerticalScroll", "SetWidth", 
    "SetZoom", "Show", "StartMoving", "StartSizing", 
    "StopMovingOrSizing", "UnlockHighlight", "UnregisterAllEvents", "UnregisterEvent", 
    "UpdateColorByID", "UpdateScrollChildRect", 
];

/// **The globals that answer a constant.**
///
/// Counted apart from [`GLOBALS`] on purpose, and this is not pedantry: a
/// function that answers a constant is indistinguishable from inside the
/// interface from one that works — `IsResting()` returning nil is not
/// "unimplemented", it is "you are not resting". Folding the two together would
/// make the completeness report improve by a hundred for work nobody did. See
/// `crates/client/src/lua/stubs.rs`, which says so in its own first line.
pub const STUBBED_GLOBALS: &[&str] = &[
    "AcceptAreaSpiritHeal", "CanJoinBattlefieldAsGroup", "CanMerchantRepair", "CheckReadyCheckTime", 
    "ConsoleExec", "CursorHasMoney", "GetAreaSpiritHealerTime", "GetBattlefieldFlagPosition", 
    "GetBattlefieldInfo", "GetBattlefieldInstanceRunTime", "GetBattlefieldPosition", "GetBattlefieldStatus", 
    "GetBattlefieldWinner", "GetBillingTimeRested", "GetChatTypeIndex", "GetChatWindowInfo", 
    "GetComboPoints", "GetCurrentMultisampleFormat", "GetCurrentResolution", "GetCursorMoney", 
    "GetDefaultLanguage", "GetGMStatus", "GetGMTicket", "GetGamma", 
    "GetGuildRecruitmentMode", "GetInventoryAlertStatus", "GetKeyRingSize", "GetLocale", 
    "GetMasterLootCandidate", "GetMultisampleFormats", "GetNetStats", "GetNumBattlefieldFlagPositions", 
    "GetNumBattlefieldPositions", "GetNumBattlefieldScores", "GetNumBattlefieldStats", "GetNumBattlefields", 
    "GetNumLaguages", "GetNumLanguages", "GetNumMapLandmarks", "GetPVPLastWeekStats", 
    "GetPVPLifetimeStats", "GetPVPRankInfo", "GetPVPRankProgress", "GetPVPSessionStats", 
    "GetPVPThisWeekStats", "GetPVPYesterdayStats", "GetQuestBackgroundMaterial", "GetQuestLogTitle", 
    "GetQuestTimers", "GetRefreshRates", "GetRepairAllCost", "GetRestState", 
    "GetScreenResolutions", "GetSelectedBattlefield", "GetSendMailItem", "GetSendMailPrice", 
    "GetSpellAutocast", "GetTrackingTexture", "GetVideoCaps", "GetWeaponEnchantInfo", 
    "HasKey", "HasSoulstone", "HideFriendNameplates", "HideNameplates", 
    "InCinematic", "IsInInstance", "IsInventoryItemLockedByPlayer", "IsMacClient", 
    "IsResting", "IsUnitOnQuest", "NoPlayTime", "OffhandHasWeapon", 
    "PartialPlayTime", "RequestBattlefieldPositions", "RequestBattlefieldScoreData", "RequestRaidInfo", 
    "SendAddonMessage", "SetBattlefieldScoreFaction", "SetChatWindowDocked", "SetChatWindowLocked", 
    "SetChatWindowShown", "SetGuildRecruitmentMode", "SetLootMethod", "SetupFullscreenScale", 
    "ShowFriendNameplates", "ShowNameplates", "ToggleSpellAutocast", "UnitHasRelicSlot", 
    "UnitIsCivilian", "UnitIsCorpse", "UnitIsPVPFreeForAll", "UnitIsTapped", 
    "UnitIsTappedByPlayer", "UnitPVPRank", "UnitPlayerOrPetInParty", "UseSoulstone", 
    "debuginfo", "debugstack", "seterrorhandler", 
];

/// …and the same bargain one layer down: the widget methods that answer a
/// constant.
pub const STUBBED_METHODS: &[&str] = &[
    "AppendText", "GetEffectiveScale", "GetFont", "GetInventorySlot", 
    "GetScale", "SetAlphaGradient", "SetDesaturated", "SetDisabledTextColor", 
    "SetHighlightTextColor", "SetMerchantCompareItem", "SetNonSpaceWrap", "SetScale", 
    "SetShapeshift", "SetTrackingSpell", 
];

/// **The events this client can raise**, from the renderer's own
/// `game::events::FIRED`.
///
/// What `--audit --events` walks, and what the unfired-event report on the HUD
/// measures a frame's registrations against. A name the interface registers for
/// that is not here is a panel quietly waiting for news that never comes.
pub const FIRED: &[&str] = &[
    "ACTIONBAR_HIDEGRID", "ACTIONBAR_PAGE_CHANGED", "ACTIONBAR_SHOWGRID", "ACTIONBAR_SLOT_CHANGED", 
    "ACTIONBAR_UPDATE_COOLDOWN", "ACTIONBAR_UPDATE_STATE", "ACTIONBAR_UPDATE_USABLE", "ADDON_LIST_UPDATE", 
    "ADDON_LOADED", "BAG_UPDATE", "BAG_UPDATE_COOLDOWN", "BANKFRAME_CLOSED", 
    "BANKFRAME_OPENED", "CANCEL_LOOT_ROLL", "CHARACTER_LIST_UPDATE", "CHARACTER_POINTS_CHANGED", 
    "CHAT_MSG_AFK", "CHAT_MSG_CHANNEL", "CHAT_MSG_CHANNEL_JOIN", "CHAT_MSG_CHANNEL_LEAVE", 
    "CHAT_MSG_CHANNEL_LIST", "CHAT_MSG_CHANNEL_NOTICE", "CHAT_MSG_CHANNEL_NOTICE_USER", "CHAT_MSG_COMBAT_CREATURE_VS_CREATURE_HITS", 
    "CHAT_MSG_COMBAT_CREATURE_VS_CREATURE_MISSES", "CHAT_MSG_COMBAT_CREATURE_VS_PARTY_HITS", "CHAT_MSG_COMBAT_CREATURE_VS_PARTY_MISSES", "CHAT_MSG_COMBAT_CREATURE_VS_SELF_HITS", 
    "CHAT_MSG_COMBAT_CREATURE_VS_SELF_MISSES", "CHAT_MSG_COMBAT_FRIENDLYPLAYER_HITS", "CHAT_MSG_COMBAT_FRIENDLYPLAYER_MISSES", "CHAT_MSG_COMBAT_FRIENDLY_DEATH", 
    "CHAT_MSG_COMBAT_HOSTILEPLAYER_HITS", "CHAT_MSG_COMBAT_HOSTILEPLAYER_MISSES", "CHAT_MSG_COMBAT_HOSTILE_DEATH", "CHAT_MSG_COMBAT_PARTY_HITS", 
    "CHAT_MSG_COMBAT_PARTY_MISSES", "CHAT_MSG_COMBAT_PET_HITS", "CHAT_MSG_COMBAT_PET_MISSES", "CHAT_MSG_COMBAT_SELF_HITS", 
    "CHAT_MSG_COMBAT_SELF_MISSES", "CHAT_MSG_COMBAT_XP_GAIN", "CHAT_MSG_DND", "CHAT_MSG_EMOTE", 
    "CHAT_MSG_GUILD", "CHAT_MSG_IGNORED", "CHAT_MSG_LOOT", "CHAT_MSG_MONSTER_EMOTE", 
    "CHAT_MSG_MONSTER_SAY", "CHAT_MSG_MONSTER_WHISPER", "CHAT_MSG_MONSTER_YELL", "CHAT_MSG_OFFICER", 
    "CHAT_MSG_PARTY", "CHAT_MSG_RAID", "CHAT_MSG_SAY", "CHAT_MSG_SKILL", 
    "CHAT_MSG_SPELL_CREATURE_VS_CREATURE_BUFF", "CHAT_MSG_SPELL_CREATURE_VS_CREATURE_DAMAGE", "CHAT_MSG_SPELL_CREATURE_VS_PARTY_BUFF", "CHAT_MSG_SPELL_CREATURE_VS_PARTY_DAMAGE", 
    "CHAT_MSG_SPELL_CREATURE_VS_SELF_BUFF", "CHAT_MSG_SPELL_CREATURE_VS_SELF_DAMAGE", "CHAT_MSG_SPELL_FRIENDLYPLAYER_BUFF", "CHAT_MSG_SPELL_FRIENDLYPLAYER_DAMAGE", 
    "CHAT_MSG_SPELL_HOSTILEPLAYER_BUFF", "CHAT_MSG_SPELL_HOSTILEPLAYER_DAMAGE", "CHAT_MSG_SPELL_PARTY_BUFF", "CHAT_MSG_SPELL_PARTY_DAMAGE", 
    "CHAT_MSG_SPELL_PERIODIC_CREATURE_BUFFS", "CHAT_MSG_SPELL_PERIODIC_CREATURE_DAMAGE", "CHAT_MSG_SPELL_PERIODIC_FRIENDLYPLAYER_BUFFS", "CHAT_MSG_SPELL_PERIODIC_FRIENDLYPLAYER_DAMAGE", 
    "CHAT_MSG_SPELL_PERIODIC_HOSTILEPLAYER_BUFFS", "CHAT_MSG_SPELL_PERIODIC_HOSTILEPLAYER_DAMAGE", "CHAT_MSG_SPELL_PERIODIC_PARTY_BUFFS", "CHAT_MSG_SPELL_PERIODIC_PARTY_DAMAGE", 
    "CHAT_MSG_SPELL_PERIODIC_SELF_BUFFS", "CHAT_MSG_SPELL_PERIODIC_SELF_DAMAGE", "CHAT_MSG_SPELL_PET_BUFF", "CHAT_MSG_SPELL_PET_DAMAGE", 
    "CHAT_MSG_SPELL_SELF_BUFF", "CHAT_MSG_SPELL_SELF_DAMAGE", "CHAT_MSG_SYSTEM", "CHAT_MSG_TEXT_EMOTE", 
    "CHAT_MSG_WHISPER", "CHAT_MSG_WHISPER_INFORM", "CHAT_MSG_YELL", "CLOSE_INBOX_ITEM", 
    "CLOSE_STATUS_DIALOG", "CLOSE_TABARD_FRAME", "CONFIRM_BINDER", "CONFIRM_LOOT_ROLL", 
    "CONFIRM_PET_UNLEARN", "CONFIRM_SUMMON", "CONFIRM_XP_LOSS", "CORPSE_IN_RANGE", 
    "CORPSE_OUT_OF_RANGE", "CRAFT_CLOSE", "CRAFT_SHOW", "CRAFT_UPDATE", 
    "CURRENT_SPELL_CAST_CHANGED", "CVAR_UPDATE", "DELETE_ITEM_CONFIRM", "DISCONNECTED_FROM_SERVER", 
    "DUEL_FINISHED", "DUEL_INBOUNDS", "DUEL_OUTOFBOUNDS", "DUEL_REQUESTED", 
    "FRAMES_LOADED", "FRIENDLIST_SHOW", "FRIENDLIST_UPDATE", "GOSSIP_CLOSED", 
    "GOSSIP_SHOW", "GUILD_INVITE_REQUEST", "GUILD_MOTD", "GUILD_REGISTRAR_CLOSED", 
    "GUILD_REGISTRAR_SHOW", "GUILD_ROSTER_UPDATE", "IGNORELIST_UPDATE", "INSPECT_HONOR_UPDATE", 
    "ITEM_LOCK_CHANGED", "ITEM_TEXT_BEGIN", "ITEM_TEXT_CLOSED", "ITEM_TEXT_READY", 
    "LOGOUT_CANCEL", "LOOT_CLOSED", "LOOT_OPENED", "LOOT_SLOT_CLEARED", 
    "MAIL_CLOSED", "MAIL_FAILED", "MAIL_INBOX_UPDATE", "MAIL_SEND_INFO_UPDATE", 
    "MAIL_SEND_SUCCESS", "MAIL_SHOW", "MERCHANT_CLOSED", "MERCHANT_SHOW", 
    "MERCHANT_UPDATE", "MINIMAP_ZONE_CHANGED", "MIRROR_TIMER_PAUSE", "MIRROR_TIMER_START", 
    "MIRROR_TIMER_STOP", "OPEN_STATUS_DIALOG", "OPEN_TABARD_FRAME", "PARTY_INVITE_REQUEST", 
    "PARTY_LEADER_CHANGED", "PARTY_LOOT_METHOD_CHANGED", "PARTY_MEMBERS_CHANGED", "PETITION_CLOSED", 
    "PETITION_SHOW", "PET_BAR_HIDEGRID", "PET_BAR_SHOWGRID", "PET_BAR_UPDATE", 
    "PET_BAR_UPDATE_COOLDOWN", "PET_STABLE_CLOSED", "PET_STABLE_SHOW", "PET_STABLE_UPDATE", 
    "PET_STABLE_UPDATE_PAPERDOLL", "PLAYERBANKBAGSLOTS_CHANGED", "PLAYERBANKSLOTS_CHANGED", "PLAYER_ALIVE", 
    "PLAYER_AURAS_CHANGED", "PLAYER_CAMPING", "PLAYER_DAMAGE_DONE_MODS", "PLAYER_DEAD", 
    "PLAYER_ENTERING_WORLD", "PLAYER_ENTER_COMBAT", "PLAYER_GUILD_UPDATE", "PLAYER_LEAVE_COMBAT", 
    "PLAYER_LEAVING_WORLD", "PLAYER_LEVEL_UP", "PLAYER_MONEY", "PLAYER_QUITING", 
    "PLAYER_TARGET_CHANGED", "PLAYER_TRADE_MONEY", "PLAYER_UNGHOST", "PLAYER_XP_UPDATE", 
    "QUEST_ACCEPT_CONFIRM", "QUEST_COMPLETE", "QUEST_DETAIL", "QUEST_FINISHED", 
    "QUEST_GREETING", "QUEST_ITEM_UPDATE", "QUEST_LOG_UPDATE", "QUEST_PROGRESS", 
    "QUEST_WATCH_UPDATE", "RAID_ROSTER_UPDATE", "RAID_TARGET_UPDATE", "READY_CHECK", 
    "RESURRECT_REQUEST", "SELECT_FIRST_CHARACTER", "SEND_MAIL_COD_CHANGED", "SEND_MAIL_MONEY_CHANGED", 
    "SET_GLUE_SCREEN", "SKILL_LINES_CHANGED", "SPELLCAST_CHANNEL_START", "SPELLCAST_CHANNEL_STOP", 
    "SPELLCAST_CHANNEL_UPDATE", "SPELLCAST_DELAYED", "SPELLCAST_FAILED", "SPELLCAST_INTERRUPTED", 
    "SPELLCAST_START", "SPELLCAST_STOP", "SPELLS_CHANGED", "SPELL_UPDATE_COOLDOWN", 
    "START_AUTOREPEAT_SPELL", "START_LOOT_ROLL", "STOP_AUTOREPEAT_SPELL", "TABARD_CANSAVE_CHANGED", 
    "TABARD_SAVE_PENDING", "TAXIMAP_CLOSED", "TAXIMAP_OPENED", "TIME_PLAYED_MSG", 
    "TRADE_ACCEPT_UPDATE", "TRADE_CLOSED", "TRADE_MONEY_CHANGED", "TRADE_PLAYER_ITEM_CHANGED", 
    "TRADE_REQUEST", "TRADE_REQUEST_CANCEL", "TRADE_SHOW", "TRADE_SKILL_CLOSE", 
    "TRADE_SKILL_SHOW", "TRADE_SKILL_UPDATE", "TRADE_TARGET_ITEM_CHANGED", "TRADE_UPDATE", 
    "TRAINER_CLOSED", "TRAINER_SHOW", "TRAINER_UPDATE", "TUTORIAL_TRIGGER", 
    "UI_ERROR_MESSAGE", "UI_INFO_MESSAGE", "UNIT_ATTACK", "UNIT_ATTACK_POWER", 
    "UNIT_ATTACK_SPEED", "UNIT_AURA", "UNIT_DAMAGE", "UNIT_DISPLAYPOWER", 
    "UNIT_ENERGY", "UNIT_FACTION", "UNIT_FOCUS", "UNIT_HAPPINESS", 
    "UNIT_HEALTH", "UNIT_INVENTORY_CHANGED", "UNIT_LEVEL", "UNIT_MANA", 
    "UNIT_MAXENERGY", "UNIT_MAXFOCUS", "UNIT_MAXHAPPINESS", "UNIT_MAXHEALTH", 
    "UNIT_MAXMANA", "UNIT_MAXRAGE", "UNIT_NAME_UPDATE", "UNIT_PET", 
    "UNIT_PET_EXPERIENCE", "UNIT_PET_TRAINING_POINTS", "UNIT_QUEST_LOG_CHANGED", "UNIT_RAGE", 
    "UNIT_RANGEDDAMAGE", "UNIT_RANGED_ATTACK_POWER", "UNIT_RESISTANCES", "UNIT_STATS", 
    "UPDATE_BINDINGS", "UPDATE_BONUS_ACTIONBAR", "UPDATE_CHAT_COLOR", "UPDATE_CHAT_WINDOWS", 
    "UPDATE_EXHAUSTION", "UPDATE_FACTION", "UPDATE_MOUSEOVER_UNIT", "UPDATE_PENDING_MAIL", 
    "UPDATE_SELECTED_CHARACTER", "UPDATE_SHAPESHIFT_FORMS", "UPDATE_TRADESKILL_RECAST", "UPDATE_WORLD_STATES", 
    "VARIABLES_LOADED", "WHO_LIST_UPDATE", "WORLD_MAP_UPDATE", "ZONE_CHANGED", 
    "ZONE_CHANGED_NEW_AREA", 
];
