//! `Light.dbc` -> `LightParams.dbc` -> `LightIntBand.dbc` + `LightFloatBand.dbc`:
//! the world's light. The chain states the sun, the ambient, the sky, the fog
//! and the colour of water; water is one of the same eighteen bands.
//!
//! Everything global about how the world is lit is in this chain, indexed by
//! map and by time of day. No other source states it: a terrain tile carries
//! normals but no light, a WMO carries baked interior colours but no sun, and
//! no packet mentions either.
//!
//! The water half of the chain is described below; the rest is
//! [`Atmosphere`]. The two share a row lookup, an interpolator and a fallback.
//!
//! ## Water colour
//!
//! The four liquid flipbooks carry no colour. `lake_a.1.blp` decodes to a peak
//! channel of 41 of 255 across the whole image, grey, with an alpha-weighted
//! mean of 7/7/7; `ocean_h` peaks at 82 and has the same shape. They are
//! luminance masks for foam and glints. A surface drawn as `texel.rgb` blended
//! over the canal bed is a black sheet at a third opacity, which looks the same
//! as a dark shadow; Stormwind's canals were drawn this way after the depth
//! fix. Lava and slime use the same code path and decode to 175/22/0 and
//! 68/132/18, which is why they were visible all along.
//!
//! The colour comes from the client's light chain, per zone and per time of
//! day, and 1.12 ships it in these tables:
//!
//! ```text
//! Light.dbc         id, mapId, x, z, y, falloffStart, falloffEnd, params[5]
//! LightParams.dbc   id, highlightSky, skyboxId, cloudType, glow,
//!                   waterShallowAlpha, waterDeepAlpha,
//!                   oceanShallowAlpha, oceanDeepAlpha
//! LightIntBand.dbc  id, entryCount, time[16], colour[16]
//! ```
//!
//! `LightIntBand` holds 18 bands per `LightParams`, which the row counts
//! confirm: 426 `LightParams` x 18 = 7,668 `LightIntBand` rows exactly, and
//! band *b* of params *p* is row `(p - 1) * 18 + b + 1`.
//!
//! The colour is packed red-first (`0x00RRGGBB`), as measured. Read the other
//! way round, map 0's noon sun (band 9) comes out pale blue and its sky top
//! (band 2) comes out brown; read red-first they are gold `228/217/179` and
//! blue `37/44/56`. Both bands are only plausible one way.
//!
//! Bands 13..16 are the water colours, and they are `close`/`far`, not
//! `shallow`/`deep`. A shallow/deep pair would darken from the first colour to
//! the second, and an earlier check assumed so. Across every default light the
//! game ships, the second of each pair is brighter in 15 of 19: the mean of
//! band 15 is `79/85/91` and of band 16 `83/79/66`. They are the near and the
//! far colour of the surface, and the far one tends toward the fog colour.
//! Depth does not affect the colour:
//!
//! ```text
//! band 13  ocean close   map 0 at noon  (97,130,183)   mean over 19 lights  76/118/145
//! band 14  ocean far                    (17, 75, 89)                       101/113/114
//! band 15  river close                  ( 0, 29, 41)                        79/ 85/ 91
//! band 16  river far                    (79, 93, 20)                        83/ 79/ 66
//! ```
//!
//! Depth drives only the alpha, between the two floats `LightParams` states
//! for the liquid. Map 0's four are 0.5 / 1.0 / 0.75 / 1.0: a river bank is
//! half transparent and the middle of a canal is opaque. Both numbers come
//! from the table. An earlier version read `MLIQ`'s depth byte directly as an
//! 8-bit alpha; the shore faded correctly, but a full canal was drawn at a
//! third opacity over a colourless texture.
//!
//! ## Clouds and sky models
//!
//! The chain also says what is drawn in the sky besides the gradient. Int bands
//! 10, 11 and 12 colour the cloud layer and float band 3 is how much of the sky
//! it covers; the layer itself is generated by [`clouds`]. `LightParams` field 2
//! names a `LightSkybox` row, a model drawn around the camera; see
//! [`SkyboxWeight`] for how the lights covering a point share the two the client
//! can draw at once, and [`skybox_models`] for the table that names the models.
//!
//! ```text
//! light/clouds.rs  the cloud texture's generator and the dome it is drawn on
//! light/tests.rs   the chain's tests
//! ```

use crate::tables::dbc::Dbc;

/// The four liquids, as [`crate::world::wmo::Liquid`] resolves them.
use crate::world::wmo::Liquid;

/// How many int bands each `LightParams` row owns. This is
/// `LightIntBand.record_count / LightParams.record_count` in 1.12, and the load
/// checks it against the files. See the module note.
pub const BANDS_PER_PARAMS: u32 = 18;

/// How many float bands each `LightParams` row owns, checked the same way:
/// `LightFloatBand.record_count / LightParams.record_count`. 1.12 ships 2,556
/// rows against 426 params rows, which is 6. This differs from the int bands'
/// 18; using the int count here would read one light's fog as another's.
pub const FLOAT_BANDS_PER_PARAMS: u32 = 6;

/// The eighteen int bands. This client reads all of them: 0..7 for the light
/// and the sky, 8 and 9 for the sun's disc and halo, 10..12 for the clouds,
/// 13..16 for the drawn water and 14..17 for the minimap bake's water. See
/// [`band::SHADOW`] on what 17 may be.
///
/// `LightIntBand` has no name column; a band is identified by its row's
/// position. Each index below was identified by measurement, printed by
/// `vale light`. A wrong index yields a plausible colour, not an error, so
/// each note records what distinguishes the band from its neighbours.
mod band {
    /// The sun: the colour of the single directional light the world is lit by.
    ///
    /// Identified by how it changes over the day. Map 0 holds `97/130/162`
    /// through the small hours (cool and dim, moonlight) and changes to
    /// `255/103/0` at 06:00 and `255/136/0` at noon. No other band does this:
    /// [`AMBIENT`] never turns warm, and the sky bands stay blue. The saturated
    /// orange is correct: it is multiplied by `N·L` and added to a cool fill,
    /// which produces the game's blue shadows.
    pub const DIFFUSE: u32 = 0;
    /// The fill: the light on every surface facing away from the sun. It is
    /// cool where the sun is warm, and darker than band 0 in 19 of 19 lights.
    pub const AMBIENT: u32 = 1;
    /// The sky dome, zenith first. The zenith is identified as the darkest of
    /// the five: map 0 at noon runs `0/31/73` at the top, then `58/162/207`,
    /// `153/220/245`, `175/218/224` and `180/180/180`. That is deep blue
    /// overhead and pale at eye level, a sky lit from beyond the horizon, which
    /// matches the game. In the reverse order it would be a sky lit from
    /// directly above the observer, which does not.
    ///
    /// The brightening is not monotonic, and checks must not require it to be:
    /// 5 is slightly darker than 4 at map 0's noon, and over the 19 defaults
    /// [`SKY_SMOG`] is darker than the band above it in 18 and [`SKY_FOG`] in
    /// 17. Those two are haze below the sky, not part of the gradient.
    pub const SKY_TOP: u32 = 2;
    pub const SKY_MIDDLE: u32 = 3;
    pub const SKY_BAND_1: u32 = 4;
    pub const SKY_BAND_2: u32 = 5;
    pub const SKY_SMOG: u32 = 6;
    /// The bottom of the dome and the colour the world fades into: one band
    /// used for both. Distant terrain disappears because it is fogged to the
    /// same colour the sky is drawn with at the horizon behind it; any other
    /// value leaves a visible line where the ground ends.
    pub const SKY_FOG: u32 = 7;
    pub const OCEAN_CLOSE: u32 = 13;
    pub const OCEAN_FAR: u32 = 14;
    pub const RIVER_CLOSE: u32 = 15;
    pub const RIVER_FAR: u32 = 16;
    /// The four water bands the shipped minimaps were rendered with. They are
    /// one row above the four bands above, and are read as a shallow and a
    /// deep colour mixed by `MCLQ`'s depth byte.
    ///
    /// Measured against the shipped minimap images, which are the retail
    /// renderer's output and so the comparison the note on
    /// [`SHADOW`](Self::SHADOW) asks for. `vale bake <Map> <x> <y> minimap`
    /// reads the shipped image where the tile's `MCLQ` places water, binned by
    /// the depth byte at each pixel. The mix that fits every band on every
    /// tile tried is `mix(band[shallow], band[deep], byte / 255)` over the
    /// ground at the float bands' opacity ramp:
    ///
    /// * Menethil's ocean (`Azeroth_33_39`, bytes under 32) reads `41/73/66`
    ///   against band 14 of the Wetlands light, `28/73/78`, over the sea
    ///   floor at 0.77;
    /// * the open sea west of it (`Azeroth_30_39`, byte 255 over 57,696
    ///   pixels) reads `0/29/41`, which is band 15 of map 0's default light
    ///   exactly, and the bytes between read the mix — `7/40/50` at 160..254
    ///   against `7/40/50` predicted;
    /// * Elwynn's lake (`Azeroth_32_49`) reads `88/89/25` at bytes under 32
    ///   against band 16, `79/93/20`, over yellow-green ground, and
    ///   `73/87/45` at 96..159 against the mix toward band 17, `51/82/85`,
    ///   predicted `72/89/46`.
    ///
    /// So band 13 is not a water colour, and the four bands this client draws
    /// water surfaces with are each one row low. The surfaces stay on the four
    /// bands above, because moving them is a renderer change that needs a
    /// screen to check against; these exist so the minimap can be drawn from
    /// the measured rows. [`LightTables::liquid_by_depth_at`] reads them.
    pub const OCEAN_SHALLOW: u32 = 14;
    pub const OCEAN_DEEP: u32 = 15;
    pub const RIVER_SHALLOW: u32 = 16;
    pub const RIVER_DEEP: u32 = 17;
    /// Unidentified. Read only so that `vale light` can print it; the renderer
    /// does not use this band.
    ///
    /// Measurements: it is dimmer than the fill in 7 of the 7 open-sky lights
    /// (`vale light` counts this beside the other four shape checks, and it
    /// fails in 3 of the 12 underground lights, as the sky checks do). It is
    /// cool where the sun is warm: map 0 at noon reads `51/82/85` against a
    /// fill of `104/130/154` and a sun of `255/136/0`. It approaches the fill
    /// as the sun goes down: half the fill's total at noon and nine tenths of
    /// it at midnight.
    ///
    /// These measurements were once read as the colour of ground in a baked
    /// `MCSH` shadow, used in place of the sun. That reading is wrong.
    /// `Shaders\Pixel\terrain1.bls`, the client's terrain fragment program,
    /// quoted in full in the renderer's `atmosphere.wgsl`, applies `MCSH` as a
    /// flat `shadow * 0.3 + 0.7` scalar over the whole modulated result. The
    /// client's terrain path has no shadow colour, so a band with the right
    /// shape for one is still not one.
    ///
    /// Open question: what row 17 is. One candidate is river-far. The
    /// canonical `LightIntBand` layout puts ocean at 14/15 and river at 16/17,
    /// one row above the four water constants above. Either those four are one
    /// row too low and every water colour this client draws is off by a band,
    /// or the canonical layout is wrong here. Settling it needs the two
    /// mappings compared against the retail client on the same server, since
    /// both produce plausible water. Until then the four above are what
    /// `vale water` measured, and this constant is named for its shape rather
    /// than for a meaning that has not been established.
    pub const SHADOW: u32 = 17;
    /// The disc of the sun: 77/77/77 on map 0 at noon, 71/71/71 over the 19
    /// defaults. Read and carried, not yet drawn: it colours the sprite
    /// `Textures\sunCenter.blp`, which needs a position over the day that this
    /// chain does not state. See [`celestial`].
    pub const SUN_DISC: u32 = 8;
    /// Its halo — 255/247/222 on map 0 at noon, 228/217/179 over the defaults:
    /// the warm glow around the disc, `Textures\sunGlare.blp`. Carried on the
    /// same terms as [`SUN_DISC`].
    pub const SUN_HALO: u32 = 9;
    /// The cloud layer's three colours; see [`super::clouds`]. Map 0 at noon
    /// holds 255/199/138, 43/105/132 and 0/0/0.
    ///
    /// Band 10 is added where a cloud's surface faces the sun or the moon.
    pub const CLOUD_HIGHLIGHT: u32 = 10;
    /// Band 11 is scaled by how thin the cloud is: fully for the thinnest,
    /// a third for the thickest.
    pub const CLOUD_SHADE: u32 = 11;
    /// Band 12 is added to every cloud texel.
    pub const CLOUD_BASE: u32 = 12;
}

/// The six float bands. Same row arithmetic as the int bands against
/// [`FLOAT_BANDS_PER_PARAMS`], and the same "the row position is the name".
mod float_band {
    /// The distance at which the world is fully fogged. Not in yards; see
    /// [`YARDS_PER_UNIT`].
    pub const FOG_END: u32 = 0;
    /// Where the fog starts, as a fraction of [`FOG_END`], so the two together
    /// form a ramp.
    ///
    /// The value can be negative, and that is what the table states, not a
    /// read error: map 0 holds 0.25 at noon and 0 or less at dawn, and Alterac
    /// Valley is negative all day. A start behind the camera means fog from the
    /// first yard: a morning mist, and the snowbound battleground. Clamped at
    /// zero on output, since nothing is nearer than the camera.
    pub const FOG_START_SCALER: u32 = 1;
    /// How much of the sky the cloud layer covers, 0 to 1. The 19 default
    /// lights hold 0.50 to 0.65; map 0's storm row holds 0.95. See
    /// [`super::clouds::CloudLight::density`].
    pub const CLOUD_DENSITY: u32 = 3;
    /// Bands 2, 4 and 5 hold 1.00, 0.95 and 1.00 in all 19 default lights and
    /// are not read.
    pub const _UNUSED: [u32; 3] = [2, 4, 5];
}

/// The name of each of the eighteen int bands, by position, for a caller that
/// labels a band it did not pick: a panel listing all eighteen, or a report
/// printing one.
///
/// The names are the [`band`] module's, where each band's measurement is
/// recorded; this is the same information as data so that nothing outside
/// this crate restates it. Bands this client does not read are named too,
/// because an unlabelled row is easy to edit by mistake.
pub const INT_BAND_NAMES: [&str; BANDS_PER_PARAMS as usize] = [
    "Sun",
    "Ambient",
    "Sky zenith",
    "Sky middle",
    "Sky band 1",
    "Sky band 2",
    "Sky smog",
    "Sky horizon and fog",
    "Sun disc",
    "Sun halo",
    "Cloud highlight",
    "Cloud shade",
    "Cloud base",
    "Ocean close",
    "Ocean far",
    "River close",
    "River far",
    "Band 17",
];

/// The names of the six float bands, on the same terms as [`INT_BAND_NAMES`].
pub const FLOAT_BAND_NAMES: [&str; FLOAT_BANDS_PER_PARAMS as usize] = [
    "Fog end",
    "Fog start scaler",
    "Float band 2",
    "Cloud density",
    "Float band 4",
    "Float band 5",
];

/// What is known about each int band beyond its name, and whether this client
/// reads it.
///
/// Kept separate from [`INT_BAND_NAMES`] because the two are used in
/// different places: a form needs the label and a report needs the sentence.
/// Empty where the name says everything.
///
/// The names and notes are kept here rather than in the caller so that there
/// is one copy. `vale light` once kept a second copy of this list, and it went
/// stale: its note on band 17 still stated the shadow-colour reading that
/// [`band::SHADOW`] records as disproved by `terrain1.bls`.
pub const INT_BAND_NOTES: [&str; BANDS_PER_PARAMS as usize] = [
    "The single directional light the world is lit by.",
    "The ambient fill. Darker than the sun in all 19 default lights.",
    "",
    "",
    "",
    "",
    "Haze below the sky, separate from the sky gradient.",
    "The horizon colour and the fog colour: one band used for both.",
    "Read but not drawn: the renderer has no sun sprite yet.",
    "Read but not drawn: the renderer has no sun glare sprite yet.",
    "Added to the clouds where they face the sun, or the moon at night.",
    "Scaled by how thin a cloud is: fully for the thinnest, a third for the thickest.",
    "Added to every cloud texel.",
    "",
    "",
    "",
    "",
    "Unidentified. Dimmer than the ambient band in all 7 open-sky lights and \
     cool where the sun is warm. It is not a shadow colour: `terrain1.bls` \
     applies MCSH as a flat scalar. It may be the far river colour; see \
     `band::SHADOW`.",
];

/// The same for the six float bands.
pub const FLOAT_BAND_NOTES: [&str; FLOAT_BANDS_PER_PARAMS as usize] = [
    "The distance at which the fog is complete, in 1/36 of a yard.",
    "Where the fog starts, as a fraction of the fog end. A negative value \
     starts the fog at the camera.",
    "Not read: flat across all 19 default lights.",
    "How much of the sky the clouds cover, 0 to 1. 0 is no clouds; the \
     default lights hold 0.5 to 0.65 and the storm rows up to 0.95.",
    "Not read: flat across all 19 default lights.",
    "Not read: flat across all 19 default lights.",
];

/// Which `LightIntBand` row holds band `band` of `LightParams` row `params`.
///
/// The band tables have no reference column; a band is found by the position
/// of its row: `(params - 1) * 18 + band + 1`, in record numbers. That is a
/// 1-based row id, equal to the id column, because the shipped tables are
/// dense and in order.
///
/// `None` for a band past the eighteenth, or for params row 0, which no light
/// names.
pub fn int_band_row(params: u32, band: u32) -> Option<u32> {
    if params == 0 || band >= BANDS_PER_PARAMS {
        return None;
    }
    Some((params - 1) * BANDS_PER_PARAMS + band + 1)
}

/// The same for the six float bands, against [`FLOAT_BANDS_PER_PARAMS`].
///
/// A separate function rather than an argument because the two counts differ
/// (18 against 6), and using the wrong one reads one light's fog as another's.
pub fn float_band_row(params: u32, band: u32) -> Option<u32> {
    if params == 0 || band >= FLOAT_BANDS_PER_PARAMS {
        return None;
    }
    Some((params - 1) * FLOAT_BANDS_PER_PARAMS + band + 1)
}

/// The inverse of [`int_band_row`]: which `(params, band)` a row id is.
///
/// For a caller that has a row in hand and has to say what it is.
pub fn int_band_of(row: u32) -> Option<(u32, u32)> {
    if row == 0 {
        return None;
    }
    Some(((row - 1) / BANDS_PER_PARAMS + 1, (row - 1) % BANDS_PER_PARAMS))
}

/// The inverse of [`float_band_row`].
pub fn float_band_of(row: u32) -> Option<(u32, u32)> {
    if row == 0 {
        return None;
    }
    Some((
        (row - 1) / FLOAT_BANDS_PER_PARAMS + 1,
        (row - 1) % FLOAT_BANDS_PER_PARAMS,
    ))
}

/// The number of key slots in a band row. `EntryCount` says how many of the
/// sixteen are live.
///
/// The slots past `EntryCount` hold leftover memory from the authoring tool
/// (`0xCCCCCCCC` in 101,116 of `LightIntBand`'s unused time slots), so a reader
/// must stop at the count and a writer must leave them unchanged.
pub const BAND_KEYS: usize = 16;

/// Where a band row's times start, and where its values start.
///
/// `id, entryCount, time[16], value[16]`. Confirmed by all 17,535 live time
/// entries of `LightIntBand` falling inside 0..[`DAY`]; the values do not.
pub const BAND_TIME_FIELD: usize = 2;
/// See [`BAND_TIME_FIELD`].
pub const BAND_VALUE_FIELD: usize = 2 + BAND_KEYS;

/// The float table's distances are in 1/36 of a yard, the same unit
/// `Light.dbc`'s coordinates are stored in. The convention belongs to this
/// chain rather than to either file.
///
/// The raw numbers name no unit, so the unit is fixed by what it makes of the
/// nineteen lights: map 0's `fogEnd` is 18,000, which as yards is four times
/// the width of the continent, and divided by 36 is 500 yards. Read that way
/// the table can be checked against the game: Scarlet Monastery fogs out at
/// 111 yards, Onyxia's Lair at 167, Dire Maul at 444, and Alterac Valley, the
/// only outdoor one of these, at 888. Read as yards they are all between four
/// and thirty times the size of their zone.
pub const YARDS_PER_UNIT: f32 = 1.0 / 36.0;

/// `LightParams` fields. 0..4 are the id, the sky flags and the glow; 5..8 are
/// the four water alphas.
pub mod params_field {
    /// The `LightSkybox` row whose model is drawn around the camera wherever
    /// this light is in force; 0 for none. Five of the 426 shipped rows name
    /// one, all of them row 3, `DeathClouds`.
    pub const SKYBOX: usize = 2;
    pub const WATER_SHALLOW_ALPHA: usize = 5;
    pub const WATER_DEEP_ALPHA: usize = 6;
    pub const OCEAN_SHALLOW_ALPHA: usize = 7;
    pub const OCEAN_DEEP_ALPHA: usize = 8;
}

/// `Light` fields: id, map, three coordinates, two falloff radii, then the five
/// `LightParams` ids: clear, clear-underwater, storm, storm-underwater, death.
///
/// The three coordinates use the same internal representation as every `MDDF`
/// and `MODF` placement in the game, `(x = westward, y = up, z = northward)`
/// measured from the map's corner, scaled by 36 like every other distance in
/// this chain. They are converted by the existing placement function,
/// [`crate::world::adt::placement_to_world`], whose note says where the
/// convention comes from and what it was checked against.
///
/// For the measurement that established this, see [`LightTables::positional`]
/// and the note on [`WORLD_CORNER`].
pub mod light_field {
    pub const MAP: usize = 1;
    /// Internal x, westward from the corner; the world's y.
    pub const INTERNAL_X: usize = 2;
    /// Internal y, which is the height, and the one column that is a plain
    /// distance rather than an offset from anything.
    pub const INTERNAL_Y: usize = 3;
    /// Internal z, northward from the corner; the world's x.
    pub const INTERNAL_Z: usize = 4;
    pub const FALLOFF_START: usize = 5;
    pub const FALLOFF_END: usize = 6;
    /// Fair weather above the surface, the ordinary case.
    pub const PARAMS_CLEAR: usize = 7;
    /// The same weather seen from under the water. This is all the 1.12.1
    /// client does for a submerged camera: a second `LightParams` row per
    /// light, with its own eighteen bands and its own two fog distances. The
    /// dome band becomes the colour of the water, the fog end drops to a few
    /// dozen yards, and the sun dims.
    ///
    /// There is no screen tint or post effect. The client has neither; it
    /// changes which light row is in force and draws the world the same way.
    /// See [`LightTables::atmosphere_in`].
    ///
    /// The last of the five, death, is the ghost world, which this client
    /// does not have. The two between are read: see [`PARAMS_STORM`].
    pub const PARAMS_CLEAR_UNDERWATER: usize = 8;
    /// The same light in bad weather. This is all the sky does when
    /// `SMSG_WEATHER` reports rain.
    ///
    /// A storm row has a darker sun, a colder fill, a dome with less blue, and
    /// fog pulled in to a fraction of the clear row's; `vale weather` prints
    /// both rows of every map side by side with the numbers. Nothing else
    /// changes: there is no darkening pass and no grey quad over the frame, as
    /// there is none underwater.
    pub const PARAMS_STORM: usize = 9;
    /// The storm row seen from under the water; a lake in a downpour needs
    /// both switches. Falls back to the clear-underwater row and then to the
    /// clear one; see [`super::Weather::of`].
    pub const PARAMS_STORM_UNDERWATER: usize = 10;
}

/// Which of the five weather columns a light is being asked for.
///
/// Four of the five: above or under the water, which the camera decides,
/// crossed with clear or storm, which the server decides through
/// `SMSG_WEATHER`. The fifth is death, and this client has no ghost world. See
/// [`light_field::PARAMS_CLEAR_UNDERWATER`] and [`light_field::PARAMS_STORM`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Weather {
    #[default]
    Clear,
    Underwater,
    Storm,
    StormUnderwater,
}

impl Weather {
    /// The clear and the storm form of this weather: the pair a blend runs
    /// between. Rain does not switch the light; it blends it toward the storm
    /// row. See [`LightTables::atmosphere_in_storm`].
    pub fn dry(self) -> (Weather, Weather) {
        match self {
            Weather::Clear | Weather::Storm => (Weather::Clear, Weather::Storm),
            Weather::Underwater | Weather::StormUnderwater => {
                (Weather::Underwater, Weather::StormUnderwater)
            }
        }
    }

    /// Pick this weather's id out of a light row's four.
    ///
    /// `[clear, clear-underwater, storm, storm-underwater]`, in the column
    /// order `Light.dbc` states them.
    fn of(self, ids: [u32; 4]) -> u32 {
        match self {
            Weather::Clear => ids[0],
            // A row that names no underwater light falls back to its own
            // clear one rather than to a guessed tint. The shipped rows fill
            // this column; a hand-made or patched row that does not should
            // look like the surface rather than like nothing.
            Weather::Underwater if ids[1] != 0 => ids[1],
            Weather::Underwater => ids[0],
            // The same rule one column along. A light with no storm row is a
            // zone whose sky does not change when it rains, which is also what
            // the 1.12.1 client draws; this client adds no darkening for it.
            Weather::Storm if ids[2] != 0 => ids[2],
            Weather::Storm => Weather::Clear.of(ids),
            Weather::StormUnderwater if ids[3] != 0 => ids[3],
            Weather::StormUnderwater => Weather::Underwater.of(ids),
        }
    }
}

/// The origin of `Light.dbc` positions: the corner of the 64x64 ADT grid,
/// which is [`crate::world::adt::MAP_ORIGIN`]. Re-exported here so that this
/// module's note has something to link to.
///
/// Measured against the server's data, not taken from a convention. The unit
/// was already fixed by the float bands ([`YARDS_PER_UNIT`]); the origin and
/// the column order are stated nowhere. Four readings of the three floats were
/// scored by taking every positional row on maps 0 and 1 and finding the
/// nearest named place in vmangos' `game_tele` table. Under this reading 186
/// of 355 rows have a named tele point inside their own falloff sphere,
/// against 66, 73 and 76 for the three alternatives.
///
/// The names are stronger evidence than the count. Under this reading light 3
/// lands 20 yards from `SwampOfSorrows`, light 5 42 from `DeadwindPass`, light
/// 39 (a 152..229 yard sphere) 71 from `BootyBay`, lights 51 and 52 (63..90
/// yards each) 52 and 54 from `DwarvenDistrict`, light 62 19 from
/// `PlaguewoodTower` and light 61 7 from `RavenholdtManor`. A wrong corner or
/// a transposed pair would not put forty small spheres on forty named
/// landmarks.
///
/// The resulting reading is exactly the existing `placement_to_world`, which
/// vmangos' `convertPositionToInternalRep` confirms. That is a second,
/// independent source, and a source file rather than a fit.
pub use crate::world::adt::MAP_ORIGIN as WORLD_CORNER;

/// A day is 2,880 half-minutes, which is the unit `LightIntBand`'s times are in.
pub const DAY: u32 = 2880;

/// Noon, used in place of a clock.
///
/// The light bands are a function of time of day and this client has no
/// day/night cycle: `SMSG_LOGIN_SETTIMESPEED` carries the server's clock and is
/// not read yet. Every screenshot in this repo was taken at noon, so noon is
/// the fixed point. When the clock is read this constant becomes an argument
/// and nothing else changes, because [`LightTables::liquid`] already
/// interpolates.
pub const NOON: u32 = DAY / 2;

/// The direction of the sun: a unit vector from the world toward the sun, in
/// the world's axes (+X north, +Y west, +Z up).
///
/// `Light.dbc` states the sun's colour at every hour and its direction at
/// none. 1.12 ships the direction already applied: every terrain chunk's
/// `MCSH` is a shadow baked for a specific sun, so the displacement between
/// tall doodads and their shadows gives the azimuth, and height against shadow
/// length gives the elevation. `vale sun` measures this and prints the result
/// against this constant, so that a difference between the two is reported.
///
/// Measured: azimuth 40 degrees (from +X north toward +Y west), elevation 40
/// degrees. Five tiles discriminate: Westfall's two give 39.0 and 38.0 deg
/// (18%/87% of predicted shadow present against 6%/45% for the opposite
/// azimuth), Durotar's gives 49.5 deg at 70% against 12%, Duskwood 32.0 and
/// the southern Barrens 43.5 with weaker contrast. The elevations of the clean
/// sparse tiles fall in 38..42. The previous guessed angle was azimuth 225,
/// which put the lit side of every wall against the baked shadow beside it.
///
/// The 1.12.1 client's lighting sun matches the bearing and not the height.
/// Its azimuth is a constant 225°, the direction light travels, which puts the
/// sun at 45°, next to 40°. Its elevation runs 20°..37° over the day
/// ([`celestial::LIGHT_POLAR`]). So this fixed direction has the right bearing
/// and stands 3° higher than the client's noon sun, and up to 20° higher than
/// its morning and evening one.
///
/// This is the sun the bakes were made for, not the renderer's. The 1.12.1
/// client's light at 17:50 travels along `(-0.6625, -0.6625, -0.3497)`,
/// azimuth 225° and 20.5° up, which matches the track to half a degree, so the
/// renderer aims its light by [`celestial::light_toward`] and follows the
/// hour. This constant is used for everything that has to agree with the
/// shipped `MCSH` and the shipped minimaps: `vale sun`, the shadow bake and
/// the minimap bake.
pub const SUN_TOWARD: [f32; 3] = [0.587, 0.492, 0.643];

/// What the game draws in the sky, and when: the stars, the sun's disc and the
/// moon's, on day-fraction curves.
///
/// `Light.dbc` states none of this: the table gives colours at an hour and
/// nothing about whether the star dome is visible. These are the 1.12.1
/// client's fixed values, which no data file states. They are reproduced
/// exactly because a star field faded on a plausible curve looks the same as
/// one faded on the right curve except at the hours where the two differ.
///
/// ## Day curves
///
/// The star dome (`Environments\Stars\stars.mdl`), the sun and moon sprites
/// (`sunCenter.blp`, `moon.blp`, `moon02.blp`) and the two glares each have a
/// four-key table of `(day fraction, value)` pairs, all evaluated the same
/// way: clamp `t` to 0..1, find the first key at or after it, wrap from the
/// last key to the first, and interpolate linearly. The star dome's opacity
/// at the hour is quantised to `value * 254 + 1`, and the dome is not drawn
/// below 2. So the fade has byte resolution and a star dome under about 0.4%
/// is skipped.
///
/// ## Positions over the day
///
/// Each body has a polar track and an azimuth track, evaluated the same way.
/// The pair gives a unit vector `(sin phi cos theta, sin phi sin theta, cos
/// phi)`, and the body is drawn in that direction at [`CELESTIAL_RADIUS`]
/// from the camera. There are three bodies, [`SUN`], [`MOON`] and
/// [`BLUE_MOON`], and each has a third track that scales its sprite. The
/// lighting sun has the same form but is a different vector; see
/// [`LIGHT_POLAR`].
pub mod celestial {
    /// The distance from the camera at which the sun and the moons are drawn,
    /// in yards: twelve.
    ///
    /// This is not a unit error. The client draws sky objects behind the world
    /// regardless of their distance, so the radius only sets how a sprite's
    /// size in yards becomes an angle on screen.
    pub const CELESTIAL_RADIUS: f32 = 12.0;

    /// π. Each track's angles are written as fractions of π so that they can
    /// be compared with the client's values directly rather than as decimals.
    const PI: f32 = std::f32::consts::PI;

    /// A day curve: `(day fraction, value)` pairs, ascending, evaluated with
    /// wrap-around.
    ///
    /// The keys are in fractions of a day (0.2291667 is 05:30), not in the
    /// half-minutes [`super::DAY`] counts. [`DayTrack::at`] takes half-minutes
    /// and divides, so nothing outside this module needs the conversion.
    pub struct DayTrack {
        pub keys: &'static [(f32, f32)],
    }

    impl DayTrack {
        /// The curve's value at an hour, in half-minutes past midnight.
        ///
        /// Wraps across midnight as the client does: a time before the first
        /// key or after the last interpolates between the last key and the
        /// first. Every one of these tracks describes the night, so the wrap
        /// is the case that matters.
        pub fn at(&self, half_minutes: u32) -> f32 {
            self.at_fraction((half_minutes % super::DAY) as f32 / super::DAY as f32)
        }

        /// The same, at a day fraction directly.
        ///
        /// Public because one body's clock is not the day: [`BLUE_MOON`] runs
        /// on a [`BLUE_MOON_PERIOD_DAYS`]-day cycle, so its tracks are sampled
        /// at a fraction that has already been through that division and
        /// cannot be expressed as half-minutes past midnight.
        pub fn at_fraction(&self, t: f32) -> f32 {
            if self.keys.is_empty() {
                return 0.0;
            }
            let t = t.clamp(0.0, 1.0);
            let last = self.keys.len() - 1;
            // The first key at or after `t`; past the end wraps to the first.
            let next = self.keys.iter().position(|(at, _)| t <= *at).unwrap_or(0);
            let prev = if next == 0 { last } else { next - 1 };
            let mut span = self.keys[next].0 - self.keys[prev].0;
            // Two keys less than 0.001 apart are a step, as in the client;
            // dividing by that span would divide by zero.
            if span.abs() < 0.001 {
                return self.keys[prev].1;
            }
            if span < 0.0 {
                span += 1.0;
            }
            let mut into = t - self.keys[prev].0;
            if into < 0.0 {
                into += 1.0;
            }
            let f = (into / span).clamp(0.0, 1.0);
            self.keys[prev].1 + (self.keys[next].1 - self.keys[prev].1) * f
        }
    }

    /// The star dome's opacity over the day.
    ///
    /// Full from midnight until 03:00, out by 04:30, dark through the day, and
    /// fading back in from 22:30 to midnight. The four times are `0.2291667`
    /// (05:30) minus 2.5 h and 1 h, and `0.8958333` (21:30) plus the same two,
    /// which is why they are not round numbers.
    ///
    /// At 22:36 this is 0.07, so the 1.12.1 client's sky is also nearly
    /// starless at that hour. Screenshots compared at that hour should show
    /// almost no stars.
    pub const STARS: DayTrack = DayTrack {
        keys: &[
            (0.125, 1.0),      // 03:00
            (0.1875, 0.0),     // 04:30
            (0.9375, 0.0),     // 22:30
            (1.0, 1.0),        // 24:00
        ],
    };

    /// The sun's glare: dark before 06:30, full from 07:30 to 19:30, out again
    /// by 21:00. Carried for when the sun disc is drawn; it is not drawn yet.
    pub const SUN_GLARE: DayTrack = DayTrack {
        keys: &[
            (0.2708333, 0.0),  // 06:30
            (0.3125, 1.0),     // 07:30
            (0.8125, 1.0),     // 19:30
            (0.875, 0.0),      // 21:00
        ],
    };

    /// The moon's glare, the inverse of the sun's: full at 02:00, gone by
    /// 03:15, dark through the day, back at 23:59.
    pub const MOON_GLARE: DayTrack = DayTrack {
        keys: &[
            (0.0833333, 1.0),  // 02:00
            (0.1354167, 0.0),  // 03:15
            (0.9479167, 0.0),  // 22:45
            (0.9993056, 1.0),  // 23:59
        ],
    };

    /// Below this the client does not draw the star dome. It is a byte rather
    /// than a fraction because the client quantises the opacity to
    /// `value * 254 + 1` and skips the draw below 2.
    ///
    /// Kept so that a dome at zero opacity is skipped rather than drawn
    /// invisibly; at noon that is every frame.
    pub const MIN_STAR_BYTE: u32 = 2;

    /// The star dome's opacity as the quantised byte, or `None` when it is
    /// under [`MIN_STAR_BYTE`] and the dome is skipped.
    pub fn star_byte(half_minutes: u32) -> Option<u32> {
        let byte = (STARS.at(half_minutes) * 254.0 + 1.0) as u32;
        (byte >= MIN_STAR_BYTE).then_some(byte)
    }

    /// The star dome model. `LightSkybox.dbc` never names it: it is the sky
    /// for every zone that names no skybox of its own. The archives hold it as
    /// an `.m2`.
    pub const STAR_MODEL: &str = r"Environments\Stars\Stars.m2";

    // --------------------------------------------------- sun and moons --

    /// One body in the sky: where it is, how large its sprite is, and which
    /// sprite it is.
    ///
    /// The client has three, [`SUN`], [`MOON`] and [`BLUE_MOON`], with the
    /// same fields and different keys, which is why this is a struct rather
    /// than nine loose constants. All three move by the same rule.
    pub struct Body {
        /// The polar angle from straight up, in radians: 0 is the zenith and
        /// π/2 the horizon, so anything over π/2 is below it. This is the
        /// client's convention, not an elevation; see [`Body::direction`].
        pub polar: DayTrack,
        /// The azimuth, in radians, measured from world +X (north) toward +Y
        /// (west). Two of the three bodies never move in it.
        pub azimuth: DayTrack,
        /// The sprite's size multiplier over the day. Both moving bodies are
        /// drawn larger near the horizon, as the eye perceives them.
        pub scale: DayTrack,
        /// A constant multiplier on top of `scale`; it makes the moon larger
        /// than the sun.
        pub base_scale: f32,
        /// The sprite.
        pub texture: &'static str,
    }

    impl Body {
        /// The body's direction as a unit vector in the world's axes (+X
        /// north, +Y west, +Z up): the frame [`super::SUN_TOWARD`] is in, and
        /// the one every placement in the game uses.
        ///
        /// `(sin φ cos θ, sin φ sin θ, cos φ)`. The client draws the body at
        /// this direction times [`CELESTIAL_RADIUS`].
        pub fn direction(&self, t: f32) -> [f32; 3] {
            let polar = self.polar.at_fraction(t);
            let azimuth = self.azimuth.at_fraction(t);
            [
                polar.sin() * azimuth.cos(),
                polar.sin() * azimuth.sin(),
                polar.cos(),
            ]
        }

        /// Height above the horizon, in degrees; negative below.
        ///
        /// The tracks are in polar angle; elevation is what checks and HUD
        /// lines use. Deriving it in one place keeps `90 - φ` from being
        /// written in several places with one of them the wrong way round.
        pub fn elevation(&self, t: f32) -> f32 {
            90.0 - self.polar.at_fraction(t).to_degrees()
        }

        /// The sprite's size multiplier at `t`.
        pub fn size(&self, t: f32) -> f32 {
            self.base_scale * self.scale.at_fraction(t)
        }
    }

    /// A day fraction from half-minutes past midnight, which is what
    /// [`Body`]'s three methods take.
    pub fn day_fraction(half_minutes: u32) -> f32 {
        (half_minutes % super::DAY) as f32 / super::DAY as f32
    }

    /// The sun: polar track (five keys), azimuth (three) and scale (four).
    ///
    /// It rises at 05:30 and sets at 21:30, and at noon climbs to within five
    /// degrees of the zenith. The three keys at 11:55, 12:00 and 12:05 form a
    /// plateau rather than a peak, which keeps it from jumping through the top
    /// of the sky. Outside that span the curve wraps between the last key and
    /// the first, both 100°, so the sun stays ten degrees below the horizon all
    /// night rather than being hidden: the client draws it and the ground
    /// occludes it.
    ///
    /// Its azimuth is constant: it rises and sets on one bearing, 45°,
    /// north-west in the world's axes. This is the bearing [`LIGHT_AZIMUTH`]
    /// puts the lighting sun at, and within five degrees of the 40° that
    /// [`super::SUN_TOWARD`] was measured at from the `MCSH` bakes. Three
    /// independent sources agree.
    pub const SUN: Body = Body {
        polar: DayTrack {
            keys: &[
                (0.2291667, PI * 0.5555556), // 05:30, 100° — ten under the horizon
                (0.4965278, PI * 0.0277778), // 11:55,   5°
                (0.5, PI * 0.0277778),       // 12:00,   5°
                (0.5034722, PI * 0.0277778), // 12:05,   5°
                (0.8958333, PI * 0.5555556), // 21:30, 100°
            ],
        },
        azimuth: DayTrack {
            keys: &[
                (0.2291667, PI * 0.25), // 05:30, 45°
                (0.5, PI * 0.25),       // 12:00, 45°
                (0.8958333, PI * 0.25), // 21:30, 45°
            ],
        },
        scale: DayTrack {
            keys: &[
                (0.25, 2.0),     // 06:00 — twice the size at the horizon
                (0.28125, 1.0),  // 06:45
                (0.84375, 1.0),  // 20:15
                (0.875, 2.0),    // 21:00
            ],
        },
        base_scale: 1.0,
        texture: r"Textures\sunCenter.blp",
    };

    /// The moon: the sun's track inverted.
    ///
    /// Above the horizon from 22:00 to 04:00, highest at midnight at 55°, and
    /// below the horizon through the day. Its azimuth is the sun's, 45°, and it
    /// is 1.75 times the size: the one difference between the two bodies that
    /// is a constant rather than a key.
    pub const MOON: Body = Body {
        polar: DayTrack {
            keys: &[
                (0.0, PI * 0.1944444),         // 00:00, 35°
                (0.0034722, PI * 0.1944444),   // 00:05, 35°
                (0.1666667, PI * 0.5555556),   // 04:00, 100°
                (0.9166667, PI * 0.5555556),   // 22:00, 100°
                (0.9965278, PI * 0.1944444),   // 23:55, 35°
            ],
        },
        azimuth: DayTrack {
            keys: &[
                (0.0, PI * 0.25),       // 00:00, 45°
                (0.1666667, PI * 0.25), // 04:00, 45°
                (0.9166667, PI * 0.25), // 22:00, 45°
            ],
        },
        scale: DayTrack {
            keys: &[
                (0.0416667, 1.0),  // 01:00
                (0.1666667, 1.5),  // 04:00 — half again at the horizon
                (0.9166667, 1.5),  // 22:00
                (0.9993056, 1.0),  // 23:59
            ],
        },
        base_scale: 1.75,
        texture: r"Textures\moon.blp",
    };

    /// The second moon. It is a separate body, not a phase of the first:
    /// `Textures\moon02.blp`, with its own azimuth track.
    ///
    /// It follows the same arc as [`MOON`], but its bearing moves from 135° to
    /// 165° as it goes, which makes it the only body in 1.12's sky whose
    /// bearing changes. Its clock is not the day: its tracks are sampled at
    /// `frac((day + t) / 1.7)`, so it is a day and a half out of step with
    /// everything else. See [`BLUE_MOON_PERIOD_DAYS`] and
    /// [`blue_moon_fraction`].
    pub const BLUE_MOON: Body = Body {
        polar: DayTrack {
            keys: &[
                (0.0, PI * 0.1944444),        // 35°
                (0.0034722, PI * 0.1944444),  // 35°
                (0.1666667, PI * 0.5555556),  // 100°
                (0.9166667, PI * 0.5555556),  // 100°
                (0.9965278, PI * 0.1944444),  // 35°
            ],
        },
        azimuth: DayTrack {
            keys: &[
                (0.0, PI * 0.75),             // 135°
                (0.1666667, PI * 0.8333333),  // 150°
                (0.9166667, PI * 0.9166667),  // 165°
            ],
        },
        scale: DayTrack {
            keys: &[
                (0.0416667, 1.0),
                (0.1666667, 1.5),
                (0.9166667, 1.5),
                (0.9993056, 1.0),
            ],
        },
        base_scale: 1.0,
        texture: r"Textures\moon02.blp",
    };

    /// The length of [`BLUE_MOON`]'s cycle, in days: 1.7.
    pub const BLUE_MOON_PERIOD_DAYS: f32 = 1.7;

    /// [`BLUE_MOON`]'s clock: its position in its own cycle, given how many
    /// whole days have passed and how far through the current day it is.
    ///
    /// Computed in `f32`; an error of a thousandth of a cycle is not
    /// measurable on screen. The day count has no source in this client yet.
    /// Passing 0 puts the blue moon at the start of its cycle, and it still
    /// moves correctly over a day, which is the visible part.
    pub fn blue_moon_fraction(days: u32, half_minutes: u32) -> f32 {
        let t = days as f32 + day_fraction(half_minutes);
        let cycles = t / BLUE_MOON_PERIOD_DAYS;
        cycles - cycles.floor()
    }

    /// The lighting sun's polar track: the same form, for a vector that is none
    /// of the three bodies above.
    ///
    /// 127° at midnight and at noon, 110° at 06:00 and 18:00, on a constant
    /// azimuth of [`LIGHT_AZIMUTH`]. Read as the direction light travels, this
    /// is a sun 20° to 37° above the horizon that never sets; night is shown
    /// entirely through colour.
    ///
    /// Used through [`light_toward`]. It was once left unused, on the argument
    /// that a light moving 17° over a day against shadows baked for one angle
    /// would look worse than a fixed light that agrees with them. The 1.12.1
    /// client's light at 17:50 travels along `(-0.6625, -0.6625, -0.3497)`,
    /// which is this track to half a degree over the same baked shadows, so
    /// the client does not use a fixed light. [`super::SUN_TOWARD`] is used
    /// only for checking against the bakes.
    pub const LIGHT_POLAR: DayTrack = DayTrack {
        keys: &[
            (0.0, PI * 0.7055556),  // 00:00, 127°
            (0.25, PI * 0.6111111), // 06:00, 110°
            (0.5, PI * 0.7055556),  // 12:00, 127°
            (0.75, PI * 0.6111111), // 18:00, 110°
        ],
    };

    /// The lighting sun's azimuth: π × 1.25, a constant 225°. That is the
    /// direction the light travels, so the sun it implies is at 45°, the same
    /// bearing [`SUN`] rises and sets on.
    pub const LIGHT_AZIMUTH: f32 = PI * 1.25;

    /// The direction toward the lighting sun at an hour, as a unit vector in
    /// the world's axes (+X north, +Y west, +Z up): the frame
    /// [`super::SUN_TOWARD`] is in and the one a `DirectionalLight` is aimed
    /// from.
    ///
    /// The client's vector is the direction light travels, `(sin φ cos θ,
    /// sin φ sin θ, cos φ)` on [`LIGHT_POLAR`] and [`LIGHT_AZIMUTH`]; this is
    /// its negation. At 17:50 it is `(0.662, 0.662, 0.350)`, and the 1.12.1
    /// client's light at that hour travels along `(-0.6625, -0.6625,
    /// -0.3497)`. The renderer uses this function to match that light.
    pub fn light_toward(half_minutes: u32) -> [f32; 3] {
        let polar = LIGHT_POLAR.at(half_minutes);
        let azimuth = LIGHT_AZIMUTH;
        [
            -(polar.sin() * azimuth.cos()),
            -(polar.sin() * azimuth.sin()),
            -polar.cos(),
        ]
    }
}

/// How many stops the sky dome has: bands 2..7, zenith to horizon.
pub const SKY_STOPS: usize = 6;

/// Where each of the six stops sits on the dome, as the sine of the altitude
/// above the horizon: 1.0 straight up, 0.0 at eye level, negative below.
///
/// This is the only number in the light chain that does not come from a file.
/// It is kept here rather than in the renderer so that there is one list to
/// correct. `LightIntBand` gives six colours and no angles, and no data file
/// states the heights of the rings of the client's sky dome. So the order
/// comes from the table and the spacing is this client's choice.
///
/// The two ends are fixed by the data:
///
/// * the last stop is [`Atmosphere::fog`], one band read twice (see
///   [`band::SKY_FOG`]), so it has to sit at altitude 0, where the fogged-out
///   terrain meets it. Any other height puts a seam along the horizon, which
///   the shared band exists to prevent.
/// * the first is the zenith and is the darkest of the six, which is how
///   [`band::SKY_TOP`] was identified.
///
/// The four between are bunched toward the horizon because the table's values
/// put them there: [`band::SKY_SMOG`] is darker than the band above it in 18
/// of the 19 default lights and [`band::SKY_FOG`] in 17. That is haze under
/// the sky rather than more sky, and haze is a thin wedge over the horizon,
/// not the top third of the sky.
pub const SKY_ALTITUDES: [f32; SKY_STOPS] = [1.00, 0.50, 0.22, 0.09, 0.03, 0.00];

/// Which int band each of those stops reads, zenith first.
///
/// Listed one by one rather than counted from [`band::SKY_TOP`], so that the
/// dome's order can be read against the table. One copy, because two functions
/// build a dome, and two lists that disagreed would put a zone's smog where
/// its zenith should be.
pub const SKY_BANDS: [u32; SKY_STOPS] = [
    band::SKY_TOP,
    band::SKY_MIDDLE,
    band::SKY_BAND_1,
    band::SKY_BAND_2,
    band::SKY_SMOG,
    band::SKY_FOG,
];

/// Everything global about how the world looks, at one place and one time.
///
/// The sun, the fill, the dome and the distance the world fades out at, all
/// from the game's tables rather than chosen here. A value picked to look
/// right in one zone is wrong in the next, and the game ships 19 default
/// lights with different daylight.
///
/// Colours are 0..1 sRGB, as the file states them. Decoding to linear, and the
/// exposure question, belong to the renderer; this module reports what the
/// table says.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Atmosphere {
    /// The sun: the colour of the one directional light the world is lit by.
    pub diffuse: [f32; 3],
    /// The fill: the light on everything facing away from the sun. Without it
    /// a north wall is black, which no screenshot of the game shows.
    pub ambient: [f32; 3],
    /// The dome, zenith first and horizon last; see [`band::SKY_TOP`].
    pub sky: [[f32; 3]; SKY_STOPS],
    /// Band 17, unidentified; see [`band::SHADOW`]. Printed by `vale light`.
    /// The renderer no longer reads it, since `MCSH` is a flat scalar with no
    /// colour.
    pub shadow: [f32; 3],
    /// The sun's disc, band 8; see [`band::SUN_DISC`]. Carried and not drawn:
    /// the sprite it colours needs a position over the day that this chain
    /// does not state. `vale sky` prints it.
    pub sun_disc: [f32; 3],
    /// The sun's halo, band 9; see [`band::SUN_HALO`]. Carried on the same
    /// terms.
    pub sun_halo: [f32; 3],
    /// Where the fog reaches full strength, in yards.
    pub fog_end: f32,
    /// Where it begins, in yards. Always `<= fog_end`; see
    /// [`float_band::FOG_START_SCALER`] for why the file stores the ratio.
    pub fog_start: f32,
    /// The cloud layer's colours, bands 10, 11 and 12; see
    /// [`band::CLOUD_HIGHLIGHT`].
    pub clouds: [[f32; 3]; 3],
    /// How much of the sky the clouds cover, float band 3. 0 for a light
    /// that states no float bands.
    pub cloud_density: f32,
    /// The sky models in force, and how strongly. See [`SkyboxWeight`].
    pub skyboxes: [SkyboxWeight; 2],
}

/// One `LightSkybox` model in force at a point, and its opacity.
///
/// A light whose `LightParams` names a skybox contributes it at the light's
/// own weight: 1 inside its inner radius, falling linearly to 0 at its outer
/// one. The client holds two such models at a time. A light adds its weight to
/// the slot already holding the same model, capped at 1, or takes an empty
/// slot; a third model is dropped. Nothing lowers a slot's weight as a later
/// light is laid over it, so a skybox fades in and out with the falloff of the
/// light that names it and with nothing else. See [`Atmosphere::add_skybox`].
///
/// The client draws a model at its weight as an opacity, and draws none of the
/// gradient dome, stars, sun, moons or clouds while any model it has loaded is
/// at 0.99 or more.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct SkyboxWeight {
    /// The `LightSkybox` row; 0 for an empty slot.
    pub id: u32,
    /// 0 to 1.
    pub weight: f32,
}

/// The weight at which a skybox hides the rest of the sky.
pub const SKYBOX_OPAQUE: f32 = 0.99;

impl Atmosphere {
    /// Fog distance for a light whose float band is missing or zero.
    ///
    /// 361 yards, the median `fogEnd` over the 19 default lights, rather than
    /// a round number, so that a missing value takes the game's typical one.
    /// The rows run from 111 yards (Scarlet Monastery) to 888 (Alterac
    /// Valley).
    pub const DEFAULT_FOG_END: f32 = 361.0;
    /// Where the fog starts, as a fraction of the end: the same median, 0.10.
    /// The game's scalers run −0.30 to 0.40; see
    /// [`float_band::FOG_START_SCALER`] for what a negative one means.
    pub const DEFAULT_FOG_START_SCALER: f32 = 0.10;

    /// What the world is lit by when the light chain states nothing: no
    /// `Light.dbc`, or a chain naming no default for any map.
    ///
    /// Each value is the mean of that band over the 19 default lights at noon,
    /// so this is the game's average daylight. It is neither white nor
    /// garish, unlike [`LiquidLight::UNLIT`]: a liquid is one surface, and a
    /// conspicuous colour on it is a useful diagnostic. This is the whole
    /// screen, and a conspicuous colour here would hide every other fault in
    /// the frame. See [`LightTables::atmosphere`].
    pub const PLACEHOLDER: Atmosphere = Atmosphere {
        diffuse: [0.80, 0.60, 0.47],
        ambient: [0.30, 0.32, 0.40],
        sky: [
            [0.14, 0.17, 0.22],
            [0.34, 0.48, 0.50],
            [0.51, 0.62, 0.58],
            [0.56, 0.70, 0.65],
            [0.49, 0.47, 0.49],
            [0.25, 0.30, 0.35],
        ],
        shadow: [0.21, 0.26, 0.27],
        sun_disc: [0.28, 0.28, 0.28],
        sun_halo: [0.89, 0.85, 0.70],
        fog_end: Atmosphere::DEFAULT_FOG_END,
        fog_start: Atmosphere::DEFAULT_FOG_END * Atmosphere::DEFAULT_FOG_START_SCALER,
        clouds: [[0.0; 3]; 3],
        cloud_density: 0.0,
        skyboxes: [SkyboxWeight { id: 0, weight: 0.0 }; 2],
    };

    /// The last stop of the dome, which is also the colour distant geometry is
    /// fogged to: one band read twice; see [`band::SKY_FOG`]. Any other colour
    /// puts a seam on the horizon.
    pub fn fog(&self) -> [f32; 3] {
        self.sky[SKY_STOPS - 1]
    }

    /// `self` moved `t` of the way toward `other`, in every field.
    ///
    /// Blended as whole atmospheres rather than band by band, which is both
    /// cheaper and safer: a positional light contributes one `LightParams` row,
    /// so mixing the results of two rows equals mixing the two rows, and doing
    /// it here means the fog distances and the six sky stops cannot be missed
    /// when a band is added. The mix is in the file's colour space, like every
    /// other sum in this chain; see the module note.
    ///
    /// The skyboxes are `self`'s. A weather blend keeps the clear row's, as the
    /// client does, and a positional light adds its own through
    /// [`Self::add_skybox`].
    pub fn mix(&self, other: &Atmosphere, t: f32) -> Atmosphere {
        let t = t.clamp(0.0, 1.0);
        let lerp = |a: f32, b: f32| a + (b - a) * t;
        let lerp3 = |a: [f32; 3], b: [f32; 3]| {
            [lerp(a[0], b[0]), lerp(a[1], b[1]), lerp(a[2], b[2])]
        };
        let mut sky = [[0.0; 3]; SKY_STOPS];
        for (stop, (a, b)) in sky.iter_mut().zip(self.sky.iter().zip(other.sky.iter())) {
            *stop = lerp3(*a, *b);
        }
        Atmosphere {
            diffuse: lerp3(self.diffuse, other.diffuse),
            ambient: lerp3(self.ambient, other.ambient),
            sky,
            shadow: lerp3(self.shadow, other.shadow),
            sun_disc: lerp3(self.sun_disc, other.sun_disc),
            sun_halo: lerp3(self.sun_halo, other.sun_halo),
            fog_end: lerp(self.fog_end, other.fog_end),
            fog_start: lerp(self.fog_start, other.fog_start),
            clouds: [
                lerp3(self.clouds[0], other.clouds[0]),
                lerp3(self.clouds[1], other.clouds[1]),
                lerp3(self.clouds[2], other.clouds[2]),
            ],
            cloud_density: lerp(self.cloud_density, other.cloud_density),
            skyboxes: self.skyboxes,
        }
    }

    /// Add a light's skybox at the light's weight, by the rule on
    /// [`SkyboxWeight`]: onto the slot holding the same model, capped at 1, or
    /// into the first empty slot, or nowhere when both hold other models.
    pub fn add_skybox(&mut self, id: u32, weight: f32) {
        if id == 0 || weight <= 0.0 {
            return;
        }
        for slot in &mut self.skyboxes {
            if slot.id == id {
                slot.weight = (slot.weight + weight).min(1.0);
                return;
            }
            if slot.id == 0 {
                *slot = SkyboxWeight { id, weight };
                return;
            }
        }
    }

    /// Whether a skybox is at a weight that hides the rest of the sky. The
    /// caller still has to check that the model loaded; the client only hides
    /// the sky behind a model it is drawing.
    pub fn skybox_opaque(&self) -> Option<u32> {
        self.skyboxes
            .iter()
            .find(|slot| slot.id != 0 && slot.weight >= SKYBOX_OPAQUE)
            .map(|slot| slot.id)
    }
}

/// One liquid's colour, and the two ends of its depth-driven opacity.
///
/// RGB is 0..1 and already lit: these come from the light chain, not from a
/// texture, so nothing multiplies them by the sun.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LiquidLight {
    /// The near colour, which a canal under the camera is drawn in.
    pub close: [f32; 3],
    /// The far colour. Carried and not yet used: mixing toward it needs the
    /// distance from the camera, a per-fragment term the liquid material does
    /// not have, and the surfaces this client draws are all within a few dozen
    /// yards. It is read now so that it is available when the terrain's `MCLQ`
    /// is drawn and oceans reach the horizon.
    pub far: [f32; 3],
    /// Opacity at `MLIQ` depth 0: the bank, where the bottom shows through.
    pub shallow_alpha: f32,
    /// Opacity at depth 255.
    pub deep_alpha: f32,
}

impl LiquidLight {
    /// What a liquid is drawn as when there is no light table.
    ///
    /// Opaque white, which is wrong and conspicuous on purpose. The
    /// alternative, the texture's own near-black colour, is the fault this
    /// module fixes, and a missing table must not reproduce a fault that cannot
    /// be seen. See [`LightTables`]' note on degradation.
    pub const UNLIT: LiquidLight = LiquidLight {
        close: [1.0, 1.0, 1.0],
        far: [1.0, 1.0, 1.0],
        shallow_alpha: 1.0,
        deep_alpha: 1.0,
    };

    /// `self` moved `t` of the way toward `other`. The water counterpart of
    /// [`Atmosphere::mix`], which says why the mix is done on the result rather
    /// than on the bands.
    pub fn mix(&self, other: &LiquidLight, t: f32) -> LiquidLight {
        let t = t.clamp(0.0, 1.0);
        let lerp = |a: f32, b: f32| a + (b - a) * t;
        let lerp3 = |a: [f32; 3], b: [f32; 3]| {
            [lerp(a[0], b[0]), lerp(a[1], b[1]), lerp(a[2], b[2])]
        };
        LiquidLight {
            close: lerp3(self.close, other.close),
            far: lerp3(self.far, other.far),
            shallow_alpha: lerp(self.shallow_alpha, other.shallow_alpha),
            deep_alpha: lerp(self.deep_alpha, other.deep_alpha),
        }
    }

    /// The colour and opacity at a given `MLIQ` depth byte.
    ///
    /// Used by `vale water` to report the ramp; the renderer does the same mix
    /// in the fragment shader off the vertex alpha, so one draw covers a canal
    /// that shallows at its banks.
    pub fn at_depth(&self, depth: u8) -> [f32; 4] {
        let t = depth as f32 / 255.0;
        [
            self.close[0],
            self.close[1],
            self.close[2],
            self.shallow_alpha + (self.deep_alpha - self.shallow_alpha) * t,
        ]
    }
}

/// One of `Light.dbc`'s positional rows: a sphere of different daylight laid
/// over the map's default.
///
/// This is how the game gives a zone its own look (Duskwood's grey,
/// Ashenvale's teal water, the warm lamplight of a city). Map 0 has 80 of them
/// and map 1 has 126, against one default each. A row is not a zone boundary:
/// the spheres cover about a tenth of map 0's tiles, and everywhere else uses
/// the default, which is also what the 1.12.1 client shows there.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PositionalLight {
    pub id: u32,
    pub map: u32,
    /// The centre, in the world's own axes and in yards. See [`WORLD_CORNER`].
    pub at: [f32; 3],
    /// The same three floats as the file states them, kept so that
    /// `vale light` can score the other readings of them against the tiles
    /// each map ships. A decode whose input is not kept cannot be checked.
    pub raw: [f32; 3],
    /// Inside this radius the row applies at full strength.
    pub falloff_start: f32,
    /// Outside this radius the row does not apply.
    pub falloff_end: f32,
    /// The `LightParams` row it names in clear weather.
    pub params: u32,
    /// The row it names for a camera under the water, a different row with
    /// its own eighteen bands; see [`light_field::PARAMS_CLEAR_UNDERWATER`].
    /// Zero for a row that states none, which [`Weather::of`] reads as "use
    /// the clear one".
    pub params_underwater: u32,
    /// The two rows the storm weather names, on the same terms; see
    /// [`light_field::PARAMS_STORM`].
    pub params_storm: u32,
    pub params_storm_underwater: u32,
}

impl PositionalLight {
    /// The row's four `LightParams` ids in `Light.dbc`'s own column order, which
    /// is what [`Weather::of`] indexes.
    pub fn params_of(&self, weather: Weather) -> u32 {
        weather.of([
            self.params,
            self.params_underwater,
            self.params_storm,
            self.params_storm_underwater,
        ])
    }
}

impl PositionalLight {
    /// How strongly this row applies at `at`: 1.0 inside `falloff_start`,
    /// falling linearly to 0.0 at `falloff_end`, and 0.0 beyond it.
    ///
    /// The distance is three-dimensional, the literal reading of a radius, and
    /// two of the rows confirm it: Ironforge's light sits at height 436 and
    /// Ironforge at 502, inside a 999..1214 yard sphere, and Un'Goro's pair are
    /// 218 yards below sea level. A horizontal-only distance would light the
    /// sky above Ironforge with the mountain's light.
    ///
    /// The ramp between the two radii is linear in distance, which is the
    /// 1.12.1 client's own falloff.
    pub fn weight(&self, at: [f32; 3]) -> f32 {
        let d = self.distance(at);
        if d <= self.falloff_start {
            return 1.0;
        }
        if d >= self.falloff_end {
            return 0.0;
        }
        // Only reachable with `falloff_start < d < falloff_end`, so the span is
        // positive; the guard is for a row whose two radii are equal or
        // reversed.
        let span = self.falloff_end - self.falloff_start;
        if span <= 0.0 {
            return 1.0;
        }
        (self.falloff_end - d) / span
    }

    /// How far `at` is from the centre, in yards, in three dimensions.
    pub fn distance(&self, at: [f32; 3]) -> f32 {
        ((self.at[0] - at[0]).powi(2) + (self.at[1] - at[1]).powi(2) + (self.at[2] - at[2]).powi(2))
            .sqrt()
    }
}

/// `LightSkybox.dbc`: each row's model, by id, as the archive path of its
/// `.m2`. The table names its models with the `.mdx` extension.
///
/// Row 4 is the star dome, which the client draws anyway; the others are
/// Stratholme, Dire Maul, the Caverns of Time, `DeathClouds`, and
/// `PortalWorldLegionSky`, a model the 1.12 archives do not hold. An empty
/// map when the table does not parse.
pub fn skybox_models(bytes: &[u8]) -> std::collections::HashMap<u32, String> {
    let Ok(table) = Dbc::parse(bytes) else {
        return std::collections::HashMap::new();
    };
    (0..table.record_count)
        .filter_map(|record| {
            let id = table.u32_at(record, 0)?;
            let name = table.string_at(record, 1)?;
            (!name.is_empty()).then(|| (id, crate::world::m2::model_path(&name)))
        })
        .collect()
}

/// The light chain, loaded once.
///
/// Optional, and its absence is a documented degradation, as for every table
/// except the three that resolve a model. Without it every liquid draws
/// [`LiquidLight::UNLIT`], a flat white sheet. That is conspicuous on purpose,
/// because the fault it replaces could not be seen.
pub struct LightTables {
    /// Per map: the ids of the `LightParams` rows the map's default light
    /// names.
    ///
    /// A map's default is the row at the origin with both falloff radii zero;
    /// vanilla ships one per map, and every other row refines it inside a
    /// sphere. Those are [`Self::positional`].
    /// `[clear, clear-underwater, storm, storm-underwater]`; see [`Weather`].
    defaults: std::collections::HashMap<u32, [u32; 4]>,
    /// Every row that is not a default: a sphere of its own daylight over the
    /// map's default, which is where a zone's own look comes from.
    ///
    /// Sorted by `falloff_end` descending at load. [`LightTables::lights_in`]
    /// orders the lights covering a point by distance; this order breaks a tie
    /// between two lights at the same distance, so that the narrower is laid
    /// last.
    positional: Vec<PositionalLight>,
    /// `LightParams` rows by id: the four water alphas.
    params: std::collections::HashMap<u32, [f32; 4]>,
    /// `LightParams` rows by id: the `LightSkybox` row each names, for the
    /// rows that name one.
    skyboxes: std::collections::HashMap<u32, u32>,
    /// `LightIntBand` rows by id: `(times, colours)`, already trimmed to the
    /// entry count the row declares.
    bands: std::collections::HashMap<u32, (Vec<u32>, Vec<u32>)>,
    /// `LightFloatBand` rows by id, the same shape with floats. May be empty,
    /// which loses the fog distances and nothing else; see
    /// [`Atmosphere::DEFAULT_FOG_END`].
    float_bands: std::collections::HashMap<u32, (Vec<u32>, Vec<f32>)>,
}

impl LightTables {
    /// Parse the chain. If any of the first three fails this returns `None`,
    /// which the caller turns into [`LiquidLight::UNLIT`] everywhere.
    ///
    /// `float_band` is the fourth and may be missing, unlike the other three:
    /// it carries two distances, and without fog the world is still drawn. The
    /// other three carry every colour, and without them there is nothing to
    /// draw the world in.
    pub fn parse(
        light: &[u8],
        params: &[u8],
        int_band: &[u8],
        float_band: &[u8],
    ) -> Option<LightTables> {
        let light = Dbc::parse(light).ok()?;
        let params_dbc = Dbc::parse(params).ok()?;
        let bands_dbc = Dbc::parse(int_band).ok()?;

        // The 18 is checked against the files rather than assumed. If a chain
        // shipped a different band count, the row arithmetic below would read
        // the next light's sky colour as water and produce a plausible wrong
        // colour.
        if params_dbc.record_count == 0
            || bands_dbc.record_count != params_dbc.record_count * BANDS_PER_PARAMS as usize
        {
            return None;
        }

        let mut defaults = std::collections::HashMap::new();
        let mut positional = Vec::new();
        for record in 0..light.record_count {
            let map = light.u32_at(record, light_field::MAP)?;
            let Some(params) = light.u32_at(record, light_field::PARAMS_CLEAR) else {
                continue;
            };
            let params_underwater = light
                .u32_at(record, light_field::PARAMS_CLEAR_UNDERWATER)
                .unwrap_or(0);
            let params_storm = light
                .u32_at(record, light_field::PARAMS_STORM)
                .unwrap_or(0);
            let params_storm_underwater = light
                .u32_at(record, light_field::PARAMS_STORM_UNDERWATER)
                .unwrap_or(0);
            let end = light.f32_at(record, light_field::FALLOFF_END).unwrap_or(0.0);
            // The default light is the one whose falloff covers nothing, which is
            // how the client marks "everywhere on this map".
            if end == 0.0 {
                defaults.entry(map).or_insert([
                    params,
                    params_underwater,
                    params_storm,
                    params_storm_underwater,
                ]);
                continue;
            }
            let coord = |field| light.f32_at(record, field).unwrap_or(0.0) * YARDS_PER_UNIT;
            positional.push(PositionalLight {
                id: light.u32_at(record, 0).unwrap_or(0),
                map,
                // Scaled from the file's 1/36 yards first, then passed through
                // the same conversion as every placement in the game; see
                // `light_field`. The height passes through unchanged, which
                // matches the rows: they run −234 to +763 yards, where a
                // corner-relative height would put every light 17 km up.
                at: crate::world::adt::placement_to_world([
                    coord(light_field::INTERNAL_X),
                    coord(light_field::INTERNAL_Y),
                    coord(light_field::INTERNAL_Z),
                ]),
                raw: [
                    light.f32_at(record, light_field::INTERNAL_X).unwrap_or(0.0),
                    light.f32_at(record, light_field::INTERNAL_Y).unwrap_or(0.0),
                    light.f32_at(record, light_field::INTERNAL_Z).unwrap_or(0.0),
                ],
                falloff_start: light
                    .f32_at(record, light_field::FALLOFF_START)
                    .unwrap_or(0.0)
                    * YARDS_PER_UNIT,
                falloff_end: end * YARDS_PER_UNIT,
                params,
                params_underwater,
                params_storm,
                params_storm_underwater,
            });
        }
        // Widest first; see the field's note, and `lights_at` for how the
        // order is used.
        positional.sort_by(|a, b| {
            b.falloff_end
                .partial_cmp(&a.falloff_end)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        let mut params = std::collections::HashMap::new();
        let mut skyboxes = std::collections::HashMap::new();
        for record in 0..params_dbc.record_count {
            let Some(id) = params_dbc.u32_at(record, 0) else {
                continue;
            };
            match params_dbc.u32_at(record, params_field::SKYBOX) {
                Some(0) | None => {}
                Some(skybox) => {
                    skyboxes.insert(id, skybox);
                }
            }
            params.insert(
                id,
                [
                    params_dbc
                        .f32_at(record, params_field::WATER_SHALLOW_ALPHA)
                        .unwrap_or(1.0),
                    params_dbc
                        .f32_at(record, params_field::WATER_DEEP_ALPHA)
                        .unwrap_or(1.0),
                    params_dbc
                        .f32_at(record, params_field::OCEAN_SHALLOW_ALPHA)
                        .unwrap_or(1.0),
                    params_dbc
                        .f32_at(record, params_field::OCEAN_DEEP_ALPHA)
                        .unwrap_or(1.0),
                ],
            );
        }

        let bands = read_band_table(&bands_dbc, |dbc, record, field| dbc.u32_at(record, field));

        // The float table is optional and is checked separately: a row count
        // that is not 6 per params row means the arithmetic would read one
        // light's fog as another's, so the table is dropped whole rather than
        // misread. Dropping it loses the two distances and nothing else.
        let float_bands = match Dbc::parse(float_band) {
            Ok(dbc) if dbc.record_count == params_dbc.record_count * FLOAT_BANDS_PER_PARAMS as usize => {
                read_band_table(&dbc, |dbc, record, field| dbc.f32_at(record, field))
            }
            _ => std::collections::HashMap::new(),
        };

        Some(LightTables {
            defaults,
            positional,
            params,
            skyboxes,
            bands,
            float_bands,
        })
    }

    /// The `LightSkybox` row a `LightParams` row names, or 0.
    pub fn skybox_of(&self, params_id: u32) -> u32 {
        self.skyboxes.get(&params_id).copied().unwrap_or(0)
    }

    /// The colour and opacity ramp for one liquid on one map, at `time`
    /// half-minutes past midnight.
    ///
    /// `None` means "draw it from its own texture", and magma and slime always
    /// return that. The reason is not a missing band: their flipbooks are the
    /// two that carry colour (peak 255 and 174, against water's 41), and their
    /// own `alphaDepth=0` already marks them opaque. Tinting them would
    /// override what the files state, and tinting them white, which is the
    /// fallback, would wash out a lava pool.
    pub fn liquid(&self, map: u32, kind: Liquid, time: u32) -> Option<LiquidLight> {
        let Some(&params_id) = self.defaults.get(&map) else {
            // Not `params_for`: a map with no light of its own gets
            // conspicuous white water rather than map 0's. This is the
            // documented difference between this fallback and `atmosphere`'s.
            return match kind {
                Liquid::Magma | Liquid::Slime => None,
                _ => Some(LiquidLight::UNLIT),
            };
        };
        // The water's colour comes from the surface light: a canal is drawn
        // from outside it, and what changes when the camera goes under is the
        // atmosphere, not the liquid material.
        self.liquid_of(Weather::Clear.of(params_id), kind, time, Self::liquid_bands(kind)?)
    }

    /// The same, refined by the position `at` on that map. This is the
    /// positional half of the chain, which gives a zone its own water
    /// (Un'Goro's green, Ashenvale's teal, Ironforge's lava-lit pools). See
    /// [`Self::lights_at`].
    ///
    /// A position no sphere covers returns exactly what [`Self::liquid`] does.
    /// That is most of every map, and it is the colour the 1.12.1 client uses
    /// there too.
    pub fn liquid_at(
        &self,
        map: u32,
        at: [f32; 3],
        kind: Liquid,
        time: u32,
    ) -> Option<LiquidLight> {
        let mut light = self.liquid(map, kind, time)?;
        let bands = Self::liquid_bands(kind)?;
        for (params, weight) in self.lights_at(map, at) {
            if let Some(refined) = self.liquid_over(&light, params, kind, time, bands) {
                light = light.mix(&refined, weight);
            }
        }
        Some(light)
    }

    /// The same liquid read as a shallow and a deep colour, from the four
    /// bands one row up; the measurement is at [`band::OCEAN_SHALLOW`].
    /// `close` is the colour at depth byte 0 and `far` the colour at 255; the
    /// two alphas are the float bands', as in [`Self::liquid_at`].
    ///
    /// This is what the shipped minimaps were rendered with, not what the
    /// client draws its surfaces with; the two read the same chain one row
    /// apart.
    pub fn liquid_by_depth_at(
        &self,
        map: u32,
        at: [f32; 3],
        kind: Liquid,
        time: u32,
    ) -> Option<LiquidLight> {
        let bands = match kind {
            Liquid::Water => (band::RIVER_SHALLOW, band::RIVER_DEEP),
            Liquid::Ocean => (band::OCEAN_SHALLOW, band::OCEAN_DEEP),
            Liquid::Magma | Liquid::Slime => return None,
        };
        let Some(&params_id) = self.defaults.get(&map) else {
            return Some(LiquidLight::UNLIT);
        };
        let mut light = self.liquid_of(Weather::Clear.of(params_id), kind, time, bands)?;
        for (params, weight) in self.lights_at(map, at) {
            if let Some(refined) = self.liquid_over(&light, params, kind, time, bands) {
                light = light.mix(&refined, weight);
            }
        }
        Some(light)
    }

    /// One `LightParams` row's liquid laid over `base`: every band the row
    /// states, and `base`'s where it states nothing. See [`Self::band`] for why
    /// that is the ordinary case rather than a fault.
    fn liquid_over(
        &self,
        base: &LiquidLight,
        params_id: u32,
        kind: Liquid,
        time: u32,
        (close_band, far_band): (u32, u32),
    ) -> Option<LiquidLight> {
        let (shallow, deep) = Self::alpha_fields(kind)?;
        let alphas = self.params.get(&params_id);
        let alpha = |field: usize, under: f32| {
            alphas
                .map(|a| a[field - params_field::WATER_SHALLOW_ALPHA])
                .unwrap_or(under)
        };
        Some(LiquidLight {
            close: self.band(params_id, close_band, time).unwrap_or(base.close),
            far: self.band(params_id, far_band, time).unwrap_or(base.far),
            shallow_alpha: alpha(shallow, base.shallow_alpha),
            deep_alpha: alpha(deep, base.deep_alpha),
        })
    }

    /// Which two bands a liquid's surface is drawn from, or `None` for the two
    /// that are drawn from their own texture.
    fn liquid_bands(kind: Liquid) -> Option<(u32, u32)> {
        match kind {
            Liquid::Water => Some((band::RIVER_CLOSE, band::RIVER_FAR)),
            Liquid::Ocean => Some((band::OCEAN_CLOSE, band::OCEAN_FAR)),
            Liquid::Magma | Liquid::Slime => None,
        }
    }

    /// Which two `LightParams` alpha fields a liquid's opacity is read from,
    /// or `None` for magma and slime.
    fn alpha_fields(kind: Liquid) -> Option<(usize, usize)> {
        match kind {
            Liquid::Water => Some((
                params_field::WATER_SHALLOW_ALPHA,
                params_field::WATER_DEEP_ALPHA,
            )),
            Liquid::Ocean => Some((
                params_field::OCEAN_SHALLOW_ALPHA,
                params_field::OCEAN_DEEP_ALPHA,
            )),
            Liquid::Magma | Liquid::Slime => None,
        }
    }

    /// One `LightParams` row's liquid, from the two bands given. `liquid` and
    /// `liquid_by_depth_at` start from it.
    fn liquid_of(
        &self,
        params_id: u32,
        kind: Liquid,
        time: u32,
        (close_band, far_band): (u32, u32),
    ) -> Option<LiquidLight> {
        let (shallow_alpha, deep_alpha) = Self::alpha_fields(kind)?;
        // The alpha fields are stored in the order this array was built in.
        let alpha_index = |field: usize| field - params_field::WATER_SHALLOW_ALPHA;

        let alphas = self
            .params
            .get(&params_id)
            .copied()
            .unwrap_or([1.0, 1.0, 1.0, 1.0]);

        Some(LiquidLight {
            close: self.band_colour(params_id, close_band, time),
            far: self.band_colour(params_id, far_band, time),
            shallow_alpha: alphas[alpha_index(shallow_alpha)],
            deep_alpha: alphas[alpha_index(deep_alpha)],
        })
    }

    /// The world's light on one map at one time: the sun, the fill, the dome
    /// and the two fog distances. See [`Atmosphere`].
    ///
    /// A map with no `Light` row of its own is given map 0's. This is a
    /// different fallback from the one [`LightTables::liquid`] takes for the
    /// same missing row, because the two serve different purposes. White water
    /// marks one surface, in a place the player may never go, and is
    /// conspicuous where it needs to be. A white sky fills the whole screen; it
    /// would look like a broken client rather than a missing row, and would
    /// hide every other fault in the frame. So this one falls back to the
    /// game's own daylight, and the count reports it: `vale light` names every
    /// map taking the fallback.
    pub fn atmosphere(&self, map: u32, time: u32) -> Atmosphere {
        self.atmosphere_weather(map, time, Weather::Clear)
    }

    /// The same, in one of the two weathers this client can be in — see
    /// [`Weather`] and [`Self::atmosphere_in`].
    pub fn atmosphere_weather(&self, map: u32, time: u32, weather: Weather) -> Atmosphere {
        match self.params_for_weather(map, weather) {
            Some(params_id) => self.atmosphere_of(params_id, time),
            None => Atmosphere::PLACEHOLDER,
        }
    }

    /// The same, refined by the position `at` on that map.
    ///
    /// Without this each continent is lit one way; with it each zone has its
    /// own light. Map 0 ships one default light and eighty spheres over it.
    /// Before the spheres were read, Stormwind, Duskwood, Westfall,
    /// Stranglethorn and Ironforge were all drawn in Elwynn's daylight.
    /// Goldshire is covered by no sphere, which is why it looked right in the
    /// screenshots in this repo while the other zones did not.
    ///
    /// See [`Self::lights_at`] for the blend and for which part of it is
    /// measured.
    pub fn atmosphere_at(&self, map: u32, at: [f32; 3], time: u32) -> Atmosphere {
        self.atmosphere_in(map, at, time, Weather::Clear)
    }

    /// The same with the weather chosen. This is all this client does for a
    /// camera under the water.
    ///
    /// `Light.dbc` states five `LightParams` ids per row, and the second is the
    /// same light seen from below the surface: its dome band is the water's
    /// colour, its fog closes to a few dozen yards, and its sun is dimmed.
    /// Nothing else changes: there is no post pass, no tinted quad and no
    /// second shader, and the 1.12.1 client has none of those either. A zone's
    /// own sphere switches with it, so diving in Un'Goro's lake and diving in
    /// the sea give different colours for the same reason they differ above
    /// the surface.
    ///
    /// Whether the camera is under the water is decided outside this module,
    /// by testing a liquid surface against the eye position. That code sits
    /// beside the mover, which asks the same question about the character's
    /// feet.
    pub fn atmosphere_in(
        &self,
        map: u32,
        at: [f32; 3],
        time: u32,
        weather: Weather,
    ) -> Atmosphere {
        let mut sky = self.atmosphere_weather(map, time, weather);
        for (params, weight) in self.lights_in(map, at, weather) {
            let over = self.atmosphere_over(&sky, params, time);
            sky = sky.mix(&over, weight);
            sky.add_skybox(self.skybox_of(params), weight);
        }
        sky
    }

    /// The same in rain: the same place lit by its clear row and by its storm
    /// row, mixed by how hard it is raining.
    ///
    /// `storm` is the weather grade, 0 for a clear sky and 1 for the strongest
    /// the server sends. At 0 this returns exactly [`Self::atmosphere_in`]
    /// (tested), so a clear day neither pays for this nor is changed by it.
    ///
    /// Data and interpretation: that `Light.dbc` carries a storm row per
    /// light, that it is column 2 of the five, and what it contains (a darker
    /// sun, a colder fill, a dome with less blue, and fog pulled in to a
    /// fraction of the clear row's) is the table, printed by `vale weather`.
    /// That the two are mixed rather than switched, and that the mix is linear
    /// in the grade, is this client's reading. It has not been confirmed
    /// whether the 1.12.1 client blends on the grade or on the density, or
    /// crossfades over a fixed time instead. The direction is not in doubt: a
    /// client that ignores the column draws Elwynn's noon behind a downpour.
    ///
    /// The grade is used rather than the density (`max(0, (g - 0.25) * 4/3)`)
    /// because the density is the particle count and is zero below a grade of
    /// a quarter. With the density, a light shower for which the 1.12.1 client
    /// draws no drops would leave the sky as bright as a clear one; with the
    /// grade the sky darkens before the first drop falls.
    pub fn atmosphere_in_storm(
        &self,
        map: u32,
        at: [f32; 3],
        time: u32,
        weather: Weather,
        storm: f32,
    ) -> Atmosphere {
        let (dry, wet) = weather.dry();
        let clear = self.atmosphere_in(map, at, time, dry);
        let storm = storm.clamp(0.0, 1.0);
        if storm <= 0.0 {
            return clear;
        }
        clear.mix(&self.atmosphere_in(map, at, time, wet), storm)
    }

    /// One `LightParams` row's atmosphere laid over `base`: every band the row
    /// states, and `base`'s where it states nothing.
    ///
    /// See [`Self::band`]: a row leaving a band empty is the ordinary case, and
    /// using [`Self::atmosphere_of`]'s white for those bands would paint the
    /// zone's sky with the marker that means "the chain is broken".
    fn atmosphere_over(&self, base: &Atmosphere, params_id: u32, time: u32) -> Atmosphere {
        let mut sky = base.sky;
        for (stop, band) in sky.iter_mut().zip(SKY_BANDS) {
            if let Some(colour) = self.band(params_id, band, time) {
                *stop = colour;
            }
        }
        // The fog start and end move together. A row stating an end and no
        // scaler would otherwise apply the base's ratio to a different
        // distance, and the zone's fog would start where neither light puts
        // it. Either both come from the row or neither does.
        let (fog_start, fog_end) = match self.band_value(params_id, float_band::FOG_END, time) {
            Some(end) if end > 0.0 => {
                let end = end * YARDS_PER_UNIT;
                let scaler = self
                    .band_value(params_id, float_band::FOG_START_SCALER, time)
                    .unwrap_or(Atmosphere::DEFAULT_FOG_START_SCALER);
                (end * scaler.clamp(0.0, 1.0), end)
            }
            _ => (base.fog_start, base.fog_end),
        };
        let cloud = |band: u32, under: [f32; 3]| self.band(params_id, band, time).unwrap_or(under);
        Atmosphere {
            clouds: [
                cloud(band::CLOUD_HIGHLIGHT, base.clouds[0]),
                cloud(band::CLOUD_SHADE, base.clouds[1]),
                cloud(band::CLOUD_BASE, base.clouds[2]),
            ],
            cloud_density: self
                .band_value(params_id, float_band::CLOUD_DENSITY, time)
                .unwrap_or(base.cloud_density),
            skyboxes: base.skyboxes,
            diffuse: self.band(params_id, band::DIFFUSE, time).unwrap_or(base.diffuse),
            ambient: self.band(params_id, band::AMBIENT, time).unwrap_or(base.ambient),
            sky,
            shadow: self.band(params_id, band::SHADOW, time).unwrap_or(base.shadow),
            sun_disc: self
                .band(params_id, band::SUN_DISC, time)
                .unwrap_or(base.sun_disc),
            sun_halo: self
                .band(params_id, band::SUN_HALO, time)
                .unwrap_or(base.sun_halo),
            fog_end,
            fog_start,
        }
    }

    /// Every positional row covering `at` on `map`, with how strongly it
    /// applies, in the order they are laid over the map's default.
    ///
    /// The order is the client's: the light whose centre is farthest from `at`
    /// first, so the nearest is laid last and wins where two cover a point at
    /// full weight. Orgrimmar stands inside Durotar's 1023..1547 yard light and
    /// its own 460..503 yard one, both at full weight and naming different
    /// `LightParams` rows; in the city its own centre is the nearer one. See
    /// [`Self::lights_in`].
    ///
    /// The weight is the client's too: 1 within the inner radius, falling
    /// linearly to 0 at the outer one, by three-dimensional distance. Each
    /// light's atmosphere is mixed over what is below it by that weight.
    pub fn lights_at(&self, map: u32, at: [f32; 3]) -> Vec<(u32, f32)> {
        self.lights_in(map, at, Weather::Clear)
    }

    /// …and in a chosen weather — the same spheres in the same order, each
    /// naming its own second row. See [`Self::atmosphere_in`].
    ///
    /// The client lays the covering lights over the default in order of their
    /// centre's distance from `at`, farthest first, so the light whose centre
    /// is nearest is laid last and wins. Two at the same distance keep the
    /// stored order, widest first.
    pub fn lights_in(&self, map: u32, at: [f32; 3], weather: Weather) -> Vec<(u32, f32)> {
        let mut covering: Vec<(f32, u32, f32)> = self
            .positional
            .iter()
            .filter(|light| light.map == map)
            .filter_map(|light| match light.weight(at) {
                w if w > 0.0 => Some((light.distance(at), light.params_of(weather), w)),
                _ => None,
            })
            .collect();
        covering.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
        covering.into_iter().map(|(_, params, w)| (params, w)).collect()
    }

    /// Every positional row on a map, widest first — for `vale light`, which
    /// checks them against the tiles the map actually has.
    pub fn positional(&self, map: u32) -> impl Iterator<Item = &PositionalLight> {
        self.positional.iter().filter(move |light| light.map == map)
    }

    /// One `LightParams` row's whole atmosphere, which the functions above
    /// start from.
    fn atmosphere_of(&self, params_id: u32, time: u32) -> Atmosphere {
        let mut sky = [[0.0; 3]; SKY_STOPS];
        for (colour, band) in sky.iter_mut().zip(SKY_BANDS) {
            *colour = self.band_colour(params_id, band, time);
        }
        // Both distances default together: a fog end with no scaler would put
        // the start at the camera and fog everything from the first yard.
        let (fog_end, scaler) = match self.band_value(params_id, float_band::FOG_END, time) {
            Some(end) if end > 0.0 => (
                end * YARDS_PER_UNIT,
                self.band_value(params_id, float_band::FOG_START_SCALER, time)
                    .unwrap_or(Atmosphere::DEFAULT_FOG_START_SCALER),
            ),
            _ => (
                Atmosphere::DEFAULT_FOG_END,
                Atmosphere::DEFAULT_FOG_START_SCALER,
            ),
        };
        let mut skyboxes = [SkyboxWeight::default(); 2];
        if let Some(&id) = self.skyboxes.get(&params_id) {
            skyboxes[0] = SkyboxWeight { id, weight: 1.0 };
        }
        Atmosphere {
            // A default light that states no cloud bands has no clouds, rather
            // than the white `band_colour` marks a missing band with.
            clouds: [
                self.band(params_id, band::CLOUD_HIGHLIGHT, time).unwrap_or([0.0; 3]),
                self.band(params_id, band::CLOUD_SHADE, time).unwrap_or([0.0; 3]),
                self.band(params_id, band::CLOUD_BASE, time).unwrap_or([0.0; 3]),
            ],
            cloud_density: self
                .band_value(params_id, float_band::CLOUD_DENSITY, time)
                .unwrap_or(0.0),
            skyboxes,
            diffuse: self.band_colour(params_id, band::DIFFUSE, time),
            ambient: self.band_colour(params_id, band::AMBIENT, time),
            sky,
            shadow: self.band_colour(params_id, band::SHADOW, time),
            sun_disc: self.band_colour(params_id, band::SUN_DISC, time),
            sun_halo: self.band_colour(params_id, band::SUN_HALO, time),
            fog_end,
            fog_start: fog_end * scaler.clamp(0.0, 1.0),
        }
    }

    /// Which `LightParams` row a map's light comes from, falling back to map 0's
    /// — see [`LightTables::atmosphere`]. `None` only if map 0 is missing too,
    /// which means the chain loaded but named no default light at all.
    pub fn params_for(&self, map: u32) -> Option<u32> {
        self.params_for_weather(map, Weather::Clear)
    }

    /// The same in a chosen weather; see [`Weather`].
    pub fn params_for_weather(&self, map: u32, weather: Weather) -> Option<u32> {
        self.defaults
            .get(&map)
            .or_else(|| self.defaults.get(&0))
            .map(|ids| weather.of(*ids))
    }

    /// Whether this map names a light row of its own, rather than borrowing map
    /// 0's. For `vale light`, which counts them.
    pub fn has_own_light(&self, map: u32) -> bool {
        self.defaults.contains_key(&map)
    }

    /// Every `LightParams` id the chain names as some map's default, for
    /// `vale water`'s band survey, which identified the four water bands among
    /// the eighteen. See the module note.
    pub fn default_params(&self) -> Vec<u32> {
        let mut ids: Vec<u32> = self.defaults.values().map(|pair| pair[0]).collect();
        ids.sort_unstable();
        ids.dedup();
        ids
    }

    /// One band of one `LightParams` row, for the same survey. `None` when the
    /// arithmetic lands outside the table.
    ///
    /// `None` also means the row states nothing about this band, which is the
    /// ordinary case and not a fault: `LightIntBand` rows carry an entry count,
    /// and only 181 of the 426 `LightParams` rows fill all eighteen. Most state
    /// fourteen to seventeen and leave the rest to whatever they are laid over:
    /// Duskwood's light says nothing about river water, Ironforge's nothing
    /// about the ocean.
    ///
    /// The distinction did not matter while the only caller was a map's
    /// default, because a default states every band. Once a positional row was
    /// read over a default, a band the row left empty showed as white water in
    /// Duskwood: [`Self::band_colour`]'s conspicuous marker in place of a band
    /// that the row left to its base.
    pub fn band(&self, params_id: u32, band: u32, time: u32) -> Option<[f32; 3]> {
        let row = params_id.checked_sub(1)? * BANDS_PER_PARAMS + band + 1;
        let (times, colours) = self.bands.get(&row)?;
        let (i, j, t) = straddle(times, colours.len(), time)?;
        let (a, b) = (unpack(colours[i]), unpack(colours[j]));
        Some([
            a[0] + (b[0] - a[0]) * t,
            a[1] + (b[1] - a[1]) * t,
            a[2] + (b[2] - a[2]) * t,
        ])
    }

    /// One int band's colour at one time. White for a band the row does not
    /// state, the same conspicuous fallback as [`LiquidLight::UNLIT`].
    ///
    /// Only for a map's default light, which states every band, so white
    /// means the chain is broken. A positional row goes through [`Self::band`]
    /// and keeps what it is laid over instead.
    fn band_colour(&self, params_id: u32, band: u32, time: u32) -> [f32; 3] {
        self.band(params_id, band, time).unwrap_or([1.0, 1.0, 1.0])
    }

    /// One float band's value at one time. `None` for a row the arithmetic
    /// misses, which is the ordinary case because the float table is optional.
    ///
    /// Public because `vale light` surveys the six float bands the same way
    /// the eighteen int bands were surveyed; that is how the bands named in
    /// [`float_band`] were identified.
    pub fn band_value(&self, params_id: u32, band: u32, time: u32) -> Option<f32> {
        let row = params_id.checked_sub(1)? * FLOAT_BANDS_PER_PARAMS + band + 1;
        let (times, values) = self.float_bands.get(&row)?;
        let (i, j, t) = straddle(times, values.len(), time)?;
        Some(values[i] + (values[j] - values[i]) * t)
    }
}

/// The two entries of a band on either side of `time`, and how far between
/// them it is. Wraps across midnight, because a band is a cycle and a time
/// past the last entry falls between it and the first.
///
/// One copy for both tables: the int and float bands need the same wrap, and
/// two copies would allow an error in one (dusk lasting until midnight, for
/// example) and not the other.
fn straddle(times: &[u32], values: usize, time: u32) -> Option<(usize, usize, f32)> {
    if times.is_empty() || values != times.len() {
        return None;
    }
    if times.len() == 1 {
        return Some((0, 0, 0.0));
    }
    let time = time % DAY;
    // The last entry to start at or before `time`; if none does, `time` is
    // before the first, so the pair is (last, first) across midnight.
    let (i, j, from, span) = match times.iter().rposition(|&t| t <= time) {
        Some(i) if i + 1 < times.len() => (i, i + 1, times[i], times[i + 1] - times[i]),
        Some(i) => (i, 0, times[i], DAY - times[i] + times[0]),
        None => {
            let last = times.len() - 1;
            (last, 0, times[last], DAY - times[last] + times[0])
        }
    };
    let elapsed = if time >= from {
        time - from
    } else {
        DAY - from + time
    };
    let t = if span == 0 {
        0.0
    } else {
        (elapsed as f32 / span as f32).clamp(0.0, 1.0)
    };
    Some((i, j, t))
}

/// One `LightIntBand` / `LightFloatBand` table, by row id.
///
/// Both files are `id, entryCount, time[16], value[16]` and differ only in how
/// the sixteen values are read, so the trimming and the 16-entry cap are stated
/// once. `read` is the cell accessor — `u32_at` for the colours, `f32_at` for
/// the distances.
fn read_band_table<T>(
    dbc: &Dbc,
    read: impl Fn(&Dbc, usize, usize) -> Option<T>,
) -> std::collections::HashMap<u32, (Vec<u32>, Vec<T>)> {
    let mut rows = std::collections::HashMap::new();
    for record in 0..dbc.record_count {
        let Some(id) = dbc.u32_at(record, 0) else {
            continue;
        };
        let count = dbc.u32_at(record, 1).unwrap_or(0).min(16) as usize;
        let times: Vec<u32> = (0..count)
            .filter_map(|i| dbc.u32_at(record, 2 + i))
            .collect();
        let values: Vec<T> = (0..count)
            .filter_map(|i| read(dbc, record, 18 + i))
            .collect();
        rows.insert(id, (times, values));
    }
    rows
}

/// A packed `LightIntBand` colour: `0x00RRGGBB`.
///
/// Confirmed from the files: map 0's ocean-shallow band at noon reads
/// (97, 130, 247) red-first and (247, 130, 97) the other way round. Ocean
/// water is the first.
fn unpack(colour: u32) -> [f32; 3] {
    [
        ((colour >> 16) & 0xFF) as f32 / 255.0,
        ((colour >> 8) & 0xFF) as f32 / 255.0,
        (colour & 0xFF) as f32 / 255.0,
    ]
}

pub mod clouds;

#[cfg(test)]
mod tests;
